### ISSUE TITLE
errors when "./CarlaUE4.sh -world-port=<port> -opengl"

### ISSUE THREAD

**Issue by shuttworth** [autonomousvision/transfuser#1]
when
`./CarlaUE4.sh -world-port=<port> -opengl`
errors happened
`bash: port: No such file or directory`

I do not know <port> how to replace

**Comment by ap229997** [comment]
Replace ```<port>``` with any suitable port number, e.g., you can just use ```--world-port=2000```

**Comment by shuttworth** [comment]
thank you for replying so soon.
when `./CarlaUE4.sh -world-port=2000 -opengl`
errors `4.24.3-0+++UE4+Release-4.24 518 0 Disabling core dumps.`
if it means it is neccessary to install the Unreal Enginee?
or I should choose the solution without display

**Comment by ap229997** [comment]
`4.24.3-0+++UE4+Release-4.24 518 0 Disabling core dumps.`
This is normal when running CARLA, it is not an error. You should be able to see the Unreal display window.

You can also check `nvidia-smi`, there should be a `CarlaUE4-Linux-Shipping` process which occupies 900-1100MB of GPU memory.
