### ISSUE TITLE
What information does json file under measurements folder store?

### ISSUE THREAD

**Issue by heminghuang7** [autonomousvision/transfuser#101]
Hello, dear author

What does the measurements folder in the dataset represent? What are the ego_matrix stands for? Can you suggest me where I can find the definition or code implementation for these?

**Comment by Kait0** [comment]
You can find the code that saves the measurements in [autopilot.py](https://github.com/autonomousvision/transfuser/blob/fe05003765294d82f03977da40767467eca53261/team_code_autopilot/autopilot.py#L304).
It mostly saves measurements about the internal state of the autopilot.
ego_matrix represents the [world matrix](https://carla.readthedocs.io/en/0.9.10/python_api/#carlatransform) of the autopilot at that frame, containing rotation and translation from the origin.
