### ISSUE TITLE
The information of topdown map

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/transfuser#105]
Thanks for your great work. I notice that the channel of top_down is set as 15 and the code only use the information of bev_array[10:12]. I'd like to konw which channel is set as the lights and road_line

**Comment by Kait0** [comment]
Some pointers to where the BEV image is created: [here](https://github.com/autonomousvision/transfuser/blob/bef1fcf5622c3ab400d4c1f27059786e7cfecb11/team_code_autopilot/utils/map_utils.py#L251), [here](https://github.com/autonomousvision/transfuser/blob/bef1fcf5622c3ab400d4c1f27059786e7cfecb11/team_code_autopilot/data_agent.py#L250) and [here](https://github.com/autonomousvision/transfuser/blob/bef1fcf5622c3ab400d4c1f27059786e7cfecb11/team_code_autopilot/data_agent.py#L440).
