### ISSUE TITLE
problem about cvpr2021 dataset

### ISSUE THREAD

**Issue by BestBUCKY** [autonomousvision/transfuser#111]
Thanks for you great work!
I notice that under the scenarios folder you provided 'all scenarios.json' for each town，did you use them to generate dataset？or only use ‘no scenarios.json' to generate dataset.

**Comment by Kait0** [comment]
For the 2021 branch:
The dataset was generated with the all scenarios files.
These are [procedurally generated](https://github.com/autonomousvision/transfuser/blob/cvpr2021/tools/generate_scenarios.py) scenarios where handcrafted scenarios were duplicated all over the map.


Regarding the 2022 branch:
The scenarios for data collection are in a different [folder](https://github.com/autonomousvision/transfuser/tree/2022/leaderboard/data/training/scenarios)
These are procedurally generated scenarios, where each is used together with its respective route file.
E.g. [route file](https://github.com/autonomousvision/transfuser/blob/2022/leaderboard/data/training/routes/Scenario1/Town01_Scenario1.xml) / [Scenario File](https://github.com/autonomousvision/transfuser/blob/2022/leaderboard/data/training/scenarios/Scenario1/Town01_Scenario1.json)

You can find out more about how the 2022 scenarios are generated [here](https://github.com/autonomousvision/transfuser/tree/2022/tools/dataset)
