### ISSUE TITLE
ask for help about low performence in 2021 branch

### ISSUE THREAD

**Issue by BestBUCKY** [autonomousvision/transfuser#115]
hello, i'm using the checkpoint your provided to evaluate in the town05, but the performence is not good.

![screenshot_2](https://user-images.githubusercontent.com/87454402/196587007-68f56fb1-4123-4675-8c0f-d0d12361019a.png)
![screenshot_3](https://user-images.githubusercontent.com/87454402/196587008-71ede6bc-5053-4c78-b140-237f08bdcf05.png)
the first is the result of Town05_short, and the other is Town05_long
and the first number is avg, the second number is std

i noticed that the agent has a high probability of blocked.
and here is the config:
`#!/bin/bash

export CARLA_ROOT=~/carla
export CARLA_SERVER=${CARLA_ROOT}/CarlaUE4.sh
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI
export PYTHONPATH=$PYTHONPATH:${CARLA_ROOT}/PythonAPI/carla
export PYTHONPATH=$PYTHONPATH:$CARLA_ROOT/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64.egg
export PYTHONPATH=$PYTHONPATH:leaderboard
export PYTHONPATH=$PYTHONPATH:leaderboard/team_code
export PYTHONPATH=$PYTHONPATH:scenario_runner

export LEADERBOARD_ROOT=leaderboard
export CHALLENGE_TRACK_CODENAME=SENSORS
export PORT=2100 # same as the carla server port
export TM_PORT=8100 # port for traffic manager, required when spawning multiple servers/clients
export DEBUG_CHALLENGE=0
export REPETITIONS=3 # multiple evaluation runs

export ROUTES=leaderboard/data/validation_routes/routes_town05_short.xml

export TEAM_AGENT=leaderboard/team_code/transfuser_agent.py # agent

export TEAM_CONFIG=models/transfuser # model checkpoint, not required for expert

export CHECKPOINT_ENDPOINT=results/routes_town05_short_transfuser_evalution.json # results file
export SCENARIOS=leaderboard/data/scenarios/town05_all_scenarios.json
export SAVE_PATH=/media/djy/H/CARLA_DATA/transfuser # path for saving episodes while evaluating

python3 ${LEADERBOARD_ROOT}/leaderboard/leaderboard_evaluator.py \
--scenarios=${SCENARIOS}  \
--routes=${ROUTES} \
--repetitions=${REPETITIONS} \
--track=${CHALLENGE_TRACK_CODENAME} \
--checkpoint=${CHECKPOINT_ENDPOINT} \
--agent=${TEAM_AGENT} \
--agent-config=${TEAM_CONFIG} \
--debug=${DEBUG_CHALLENGE} \
--record=${RECORD_PATH} \
--resume=${RESUME} \
--port=${PORT} \
--trafficManagerPort=${TM_PORT}`

and i run it using single 3080ti gpu

can you give me some suggestions?
Thanks for your attention

**Comment by ap229997** [comment]
The transfuser checkpoint in the 2021 branch is different than the one used for results in the paper. We later updated the checkpoint with the model that was submitted to the leaderboard and that was trained in a different setting than what is mentioned in the paper. I'd suggest shifting to the 2022 branch since it contains all the latest models, checkpoints and contains fixes for several bugs in the 2021 branch.

**Comment by BestBUCKY** [comment]
Thanks for your reply, i will shift to the 2022 branch
