### ISSUE TITLE
Evaluation on leaderboard

### ISSUE THREAD

**Issue by NavoditC** [autonomousvision/transfuser#116]
Hi,

I am using the code provided in the cvpr2021 branch and wanted to evaluate it on the leaderboard. I am facing issues in generating the docker image and will briefly describe what I did.

I created a new directory called team_code in the home directory which contains the transfuser_agent.py file and the model_ckpt folder(which contains the transfuser folder having the model.pth file inside it). I made changes in Dockerfile.master, make_docker.sh and run_evaluation.sh located in leaderboard -->scripts:

In **Dockerfile.master** I made the following changes:

############                                BEGINNING OF USER COMMANDS                                    ############

ENV TEAM_AGENT team_code/transfuser_agent.py
ENV TEAM_CONFIG team_code/model_ckpt/transfuser
ENV CHALLENGE_TRACK_CODENAME SENSORS

############                                   END OF USER COMMANDS                                              ############

In **make_docker.sh** file I added the following:

export CARLA_ROOT=carla
export SCENARIO_RUNNER_ROOT=scenario_runner
export LEADERBOARD_ROOT=leaderboard
export TEAM_CODE_ROOT=team_code
export PYTHONPATH="${CARLA_ROOT}/PythonAPI/carla/":"${SCENARIO_RUNNER_ROOT}":"${LEADERBOARD_ROOT}":${PYTHONPATH}

The **run_evaluation.sh** file incorporates the changes listed [here](https://github.com/autonomousvision/transfuser/tree/cvpr2021/transfuser) with the exception that TEAM_AGENT and TEAM_CONFIG have been modified and look like this:

export TEAM_AGENT=team_code/transfuser_agent.py
export TEAM_CONFIG=team_code/model_ckpt/transfuser

On running **./leaderboard/scripts/make_docker.sh** on the terminal, I get the following error message:

mv: target '.tmp/PythonAPI/carla/dist/carla-leaderboard.egg' is not a directory
Sending build context to Docker daemon  107.8GB
Step 1/38 : FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> b13c2165c94f
Step 2/38 : ARG HTTP_PROXY
 ---> Using cache
 ---> 089364e0014b
Step 3/38 : ARG HTTPS_PROXY
 ---> Using cache
 ---> 4b571fa3f2f6
Step 4/38 : ARG http_proxy
 ---> Using cache
 ---> 802df810d3e4
Step 5/38 : RUN apt-get update && apt-get install --reinstall -y locales && locale-gen en_US.UTF-8
 ---> Using cache
 ---> 6cbb2eba891c
Step 6/38 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 799289fd0897
Step 7/38 : ENV LANGUAGE en_US
 ---> Using cache
 ---> 8ffb0c09f4a9
Step 8/38 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> feb64f336835
Step 9/38 : RUN apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          vim          ca-certificates          libjpeg-dev     libpng16-16     libtiff5          libpng-dev          python-dev          python3.5          python3.5-dev          python-networkx          python-setuptools          python3-setuptools          python-pip          python3-pip &&          pip install --upgrade pip &&          pip3 install --upgrade pip &&          rm -rf /var/lib/apt/lists/*
 ---> Running in 4be7171a2f2b
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease [1,581 B]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Get:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release [564 B]
Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release
Fetched 299 kB in 0s (304 kB/s)
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
W: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease' is not signed.

I updated the CUDA Linux GPG Repository Key referencing this [blog](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/) but the error still persists. Could you please tell what might be potentially going wrong?

**Comment by Kait0** [comment]
I don't think the dockerfile master in the 2021 branch still works.
This original dockerfile released by the CARLA team depends on old software some of which is deprecated by now and not available anymore in the standard form.

I would recommend you try the Dockerfile.master in the 2022 branch instead, we updated it to fix some of these problems.

I also don't quite get why you would want to submit a 2021 branch model to the leaderboard.
The models from the 2021 branch get around 15-20 DS on the leaderboard, whereas models from the 2022 branch get around 50-60 DS.

**Comment by NavoditC** [comment]
Thank you for your suggestion. I was using the 2021 branch model because when I started my research project the 2022 branch was being updated by the authors. Anyway, I'll now use the 2022 branch and hopefully everything should work well.
