### ISSUE TITLE
ask for help about the segmentation data

### ISSUE THREAD

**Issue by BestBUCKY** [autonomousvision/transfuser#119]
hello，i‘m using the autopilot agent you provided to generate dataset, but the segmentation data seems have problem.
this is rgb
![image](https://user-images.githubusercontent.com/87454402/199415416-3e90721e-a648-4955-857d-6f029125a6e1.png)
this raw segmentaion
![image](https://user-images.githubusercontent.com/87454402/199415440-bc546dfd-63eb-416a-9682-fffa26233c15.png)
this processed segmentation
![image](https://user-images.githubusercontent.com/87454402/199415465-7cff31b7-d3a4-47ef-b4ab-d3ffa599cee6.png)

there are many points be considered as Unlabeled, what should i do?

thanks for your attention

**Comment by kashyap7x** [comment]
This is an unreal engine bug related to your GPU hardware, see https://github.com/carla-simulator/carla/issues/4328

It seems to often be fixed when launching the CARLA server with the "-opengl" flag, make sure you are doing this. Further, the issue seems to only affect newer GPUs (30xx series).

**Comment by BestBUCKY** [comment]
thanks for your reply.
i have launched the CARLA server with ‘opengl’ flag, and this problem arises.
my GPU is 3080ti   :(

**Comment by BestBUCKY** [comment]
This problem seems difficult to solve.
i notice that CARLA Leaderbroad2.0 is using CARLA9.13, which support 30 series GPU,  Will your future work be based on the CARLA Leaderbroad2.0 ?

**Comment by kashyap7x** [comment]
Our short-term plan is to continue on Leaderboard 1.0 until we resolve the failures of our current systems on that benchmark. We may move to Leaderboard 2.0 next year.

**Comment by BestBUCKY** [comment]
Look forward to your future work！
