### ISSUE TITLE
CUDA VERSION

### ISSUE THREAD

**Issue by ggosjw** [autonomousvision/transfuser#121]
Thank you for open sourcing your amazing work.

Could you upload a new version of environment.yaml which is based on CUDA 11.3 ?
Because I my PC cannot reproduce your amazing work based on CUDA 10.2. 

Thank you in advance!

**Comment by Kait0** [comment]
See https://github.com/autonomousvision/transfuser/issues/114#issuecomment-1277619389 .

**Comment by ggosjw** [comment]
thanks!
