### ISSUE TITLE
Questions about training with downloaded data

### ISSUE THREAD

**Issue by ggosjw** [autonomousvision/transfuser#122]
Hi, thank you for opening source your great work.

I have an issue regarding the training with downloaded dataset. 
I use the command chmod +x download_data.sh   and ./download_data.sh to download your dataset.
The downloaded dataset looks like this 
![image](https://user-images.githubusercontent.com/87901530/201014870-b7ff4cdd-61a0-40cc-b405-420bcab9953a.png)
And i encounter following ValueError when trying to train:
![image](https://user-images.githubusercontent.com/87901530/201015465-c34adf3a-e69c-4cbe-b287-948bfee5e461.png)

So could you give me some suggestions regarding this situation?

Thank you in advance for your kind help!

**Comment by kashyap7x** [comment]
Please set the `root_dir` arg to the parent folder of your download, `/home/arc/transfuser/data/`.

**Comment by ggosjw** [comment]
Thank you very much!
Thanks again for your great work!
