### ISSUE TITLE
problem in evaluation

### ISSUE THREAD

**Issue by xanhug** [autonomousvision/transfuser#128]
thanks for your amazing work!
when i try to operate the "local_evaluation.sh" as the instruction by
`/local_evaluation.sh /home/hxa/TF/transfuser/carla /home/hxa/TF/transfuser`
i found that nothing is happen except carla's view is changed into here;
there is no ego agent or other vehicles.
![2022-11-27 11-17-05 的屏幕截图](https://user-images.githubusercontent.com/109917206/204117653-a0052e15-7460-496d-823a-9fe682c3254d.png)
and the code is like this:
```
(tfuse) hxa@hxa-Nitro-AN515-58:~/TF/transfuser/leaderboard/scripts$ ./local_evaluation.sh /home/hxa/TF/transfuser/carla /home/hxa/TF/transfuser
/home/hxa/TF/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py:89: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):
> Registering the global statistics
(tfuse) hxa@hxa-Nitro-AN515-58:~/TF/transfuser/leaderboard/scripts$
```

i wonder if the carla will running like the video https://www.youtube.com/watch?v=DZS-U3-iV0s&list=PL6LvknlY2HlQG3YQ2nMIx7WcnyzgK9meO if my code working normally?
what should i do now to perform the evaluation normally?

i'm sorry for my poor english,hope i could describe my problem clearly.

i have tried to borwse other issues and modify
`export RESUME=0`
but it seems not work

when i tried to use carla in low-level quality model to evaluate, the result is like i mentioned above,and i found if i try to use carla not in low-level quality to evaluate,it's crash.
```
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
LowLevelFatalError [File:Unknown] [Line: 3762] 
Failed to link program [Program V_3AA5F7CCAD2B351344BE53DDA22E8BAEBA78720A_P_ABADFE631118A2CF0719C49D3F936DABF0CE8865]. Current total programs: 268, precompile: 0
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=144272 LargeMemoryPoolOffset=275408 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

```

my gpu is 3060(laptop)(6g)
i don't know if my gpu memory is too slow to evaluate in carla with normal quality,and if i could evaluate normally in carla with low-quality model.

**Comment by Kait0** [comment]
GPU memory should be fine I can also run these models on my old 980 with 4 GB in high quality.

I would suggest you to use a debugger and debug in the leaderboard_evaluator_local.py file to see why it directly skips to the 

> Registering the global statistics

step.
The program should go to [this function](https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/leaderboard/leaderboard/leaderboard_evaluator_local.py#L411):

**Comment by xanhug** [comment]
> 

thanks for your reply!
i'll try to check it as your suggestion.

**Comment by xanhug** [comment]
> GPU memory should be fine I can also run these models on my old 980 with 4 GB in high quality.
> 
> I would suggest you to use a debugger and debug in the leaderboard_evaluator_local.py file to see why it directly skips to the
> 
> > Registering the global statistics
> 
> step. The program should go to [this function](https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/leaderboard/leaderboard/leaderboard_evaluator_local.py#L411):

i have try to redownload transfuser and follow the readme.md, and this time i running the "local_evaluation.sh", something is different,seems it's also a question about gpu memory?
![2022-12-01 14-34-10 的屏幕截图](https://user-images.githubusercontent.com/109917206/204986756-c32ec60c-3131-493b-a6e7-dcbb576a6aad.png)
![2022-12-01 15-00-04 的屏幕截图](https://user-images.githubusercontent.com/109917206/204986782-fd4ed664-2002-4775-a690-e7a4aded218d.png)

```
(tfuse) hxa@hxa-Nitro-AN515-58:~/TF1/transfuser$ ./leaderboard/scripts/local_evaluation.sh /home/hxa/TF1/transfuser/carla /home/hxa/TF1/transfuser
/home/hxa/TF1/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py:89: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):

========= Preparing RouteScenario_5 (repetition 0) =========
> Setting up the agent
/home/hxa/TF1/transfuser/model_ckpt/transfuser/model_seed3_37.pth
/home/hxa/TF1/transfuser/model_ckpt/transfuser/model_seed1_39.pth
/home/hxa/TF1/transfuser/model_ckpt/transfuser/model_seed2_39.pth

Could not set up the required agent:
> CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.81 GiB total capacity; 2.67 GiB already allocated; 50.94 MiB free; 2.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "/home/hxa/TF1/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 271, in _load_and_run_scenario
    self.agent_instance = getattr(self.module_agent, agent_class_name)(args.agent_config)
  File "/home/hxa/TF1/transfuser/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45, in __init__
    self.setup(path_to_conf_file)
  File "/home/hxa/TF1/transfuser/team_code_transfuser/submission_agent.py", line 94, in setup
    state_dict = torch.load(os.path.join(path_to_conf_file, file), map_location='cuda:0')
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 1046, in _load
    result = unpickler.load()
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 1016, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 970, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 176, in default_restore_location
    result = fn(storage, location)
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/serialization.py", line 158, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/hxa/anaconda3/envs/tfuse/lib/python3.7/site-packages/torch/cuda/__init__.py", line 661, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.81 GiB total capacity; 2.67 GiB already allocated; 50.94 MiB free; 2.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Registering the route statistics

========= Preparing RouteScenario_6 (repetition 0) =========
> Setting up the agent
/home/hxa/TF1/transfuser/model_ckpt/transfuser/model_seed3_37.pth
/home/hxa/TF1/transfuser/model_ckpt/transfuser/model_seed1_39.pth
^Z

```

when i training with the dataset(210g) few days before,i had encounter similar question,but i finally training successfully by decrease batch_size to '2'
this time, i try to set the batch_size to '2' in the 'args.txt', but it seems not work? could you tell me what should i do please?thanks for your help again.

**Comment by xanhug** [comment]
> GPU memory should be fine I can also run these models on my old 980 with 4 GB in high quality.
> 
> I would suggest you to use a debugger and debug in the leaderboard_evaluator_local.py file to see why it directly skips to the
> 
> > Registering the global statistics
> 
> step. The program should go to [this function](https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/leaderboard/leaderboard/leaderboard_evaluator_local.py#L411):

there are 3 pth files
![2022-12-01 19-59-56 的屏幕截图](https://user-images.githubusercontent.com/109917206/205047686-aa268663-4bbd-4070-a8db-6500114c2945.png)
and i only keep one in this directory
![2022-12-01 20-00-17 的屏幕截图](https://user-images.githubusercontent.com/109917206/205047852-3688ff0b-6406-4703-a5ef-ef0258851d44.png)
now it seems get to next step like that 
![2022-12-01 19-59-31 的屏幕截图](https://user-images.githubusercontent.com/109917206/205047956-6eec3f35-00e0-4c80-bead-91b4ab62631e.png)
is that right? it seems different from the YOUTUBE video like https://www.youtube.com/watch?v=DZS-U3-iV0s&list=PL6LvknlY2HlQG3YQ2nMIx7WcnyzgK9meO
in this video,there are depth graph, point cloud graph and the perspective is different too. So i don't know if my evaluation program running correctly.

**Comment by kashyap7x** [comment]
The CARLA display you get is correct. Removing the 2 pth files makes the code evaluate a single model rather than the ensemble of 3 models which reduces the memory requirement.

We generated the YouTube videos by saving the model inputs and outputs to the disk while evaluating, using this function:
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L935
You can enable the visualization by adding a `SAVE_PATH` environment variable to `local.evaluation.sh`. The visualized frames will be stored in this `SAVE_PATH`. Keep in mind that enabling the visualization will slow down the evaluation.

**Comment by xanhug** [comment]
> 

i got it,thanks a lot.
