### ISSUE TITLE
Is the CARLA Leaderboard still available on Alpha Drive?

### ISSUE THREAD

**Issue by KP-Zhang** [autonomousvision/transfuser#137]
Thank you for your code. It is very helpful.
We have already trained our model on our local computer. We are going to evaluate our model in the CARLA Leaderboard via Alpha Drive. To submit our Docker image, we created a team last week. However, our team still have not been approved. Is the CARLA Leaderboard still available?
![image](https://user-images.githubusercontent.com/23057231/209748633-c6d2963d-134f-449b-ba6d-078a21d24b33.png)
Thank you for your time.

**Comment by Kait0** [comment]
As far as I am aware the leaderboard is still available.
The tutorial for the submission can be found [here](https://leaderboard.carla.org/submit_v1/).
For problems regarding the leaderboard you should contact the maintainers.
Guillermo López, Joel Moriana or German Ros are the people you need to talk to.
You can do that via their [e-mail](https://leaderboard.carla.org/help/) or the [CARLA discord](https://discord.com/invite/8kqACuC)
In Europe we currently have the christmas holidays and people are usually on vacation.
I presume that this is the reason why your approval takes so long.

**Comment by KP-Zhang** [comment]
Thanks a lot for your information.
