### ISSUE TITLE
Hi, when I started the training progress, I met an error about cuda. Could you please tell me which version of cuda do you use? 

### ISSUE THREAD

**Issue by elegentbamboo** [autonomousvision/transfuser#14]
I use a single GPU RTX3080, and cuda10.1, cudnn7.6.3, and torch1.4.0 as you specify in requirements.txt. 
When I ran train.py to train the transfuser model, an error occurred: RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED. 
After searching this error, I set *torch.backends.cudnn.enabled=false*, but another error came: RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`. I guess it is the problem of version.

**Comment by ap229997** [comment]
I'd suggest updating cuda, cudnn, and torch to the latest version. I've seen cases where older cuda versions give errors when running on RTX 3080.
