### ISSUE TITLE
The command in the dataset

### ISSUE THREAD

**Issue by ZHICHENG12** [autonomousvision/transfuser#144]
In the dataset measurement.json, what does command: 4 mean?
Does 1, 2, 3, 4 mean go straight, left turn, right turn, and lane maintenance？
![q](https://user-images.githubusercontent.com/94674786/218939764-575e7fdd-9b2d-4888-b22a-39c527042156.png)

**Comment by Kait0** [comment]
-1: VOID, 1: LEFT, 2: RIGHT, 3: STRAIGHT, 4: LANEFOLLOW, 5: CHANGELANELEFT, 6: CHANGELANERIGHT
