### ISSUE TITLE
draw waypoints on BEV

### ISSUE THREAD

**Issue by SmashChen** [autonomousvision/transfuser#147]
Thanks for your contribution, I would like to ask how is the HD Map obtained ？and how to draw waypoints on BEV?

**Comment by kashyap7x** [comment]
The HD map is obtained using a small convolutional decoder on our learned BEV features, followed by interpolation:
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L721

The visualization (including HD map predictions and BEV waypoints) is implemented here:
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L935
