### ISSUE TITLE
Data Set connection issue

### ISSUE THREAD

**Issue by charles-pyj** [autonomousvision/transfuser#151]
Hi, I tried to run transfuser on my server but my attemption to download the dataset failed with error code 403.  Could you offer some suggestions?
![180c2da70e6038649f8484e568641a1](https://user-images.githubusercontent.com/46083650/228764473-61cf7b6c-3a02-4e9e-b9ec-56a776d57fcc.png)

**Comment by Kait0** [comment]
Maybe related to https://github.com/autonomousvision/transfuser/issues/94 ?
