### ISSUE TITLE
IndexError during training

### ISSUE THREAD

**Issue by JianLiMech** [autonomousvision/transfuser#152]
Hi, I have tried to train your model with 2 dataset (left and ll), but I cannot run the training since :
![image](https://user-images.githubusercontent.com/105591726/229642056-2eabdd9c-a98f-478f-ac17-c5a2880ad7b3.png)

Have you met this problem during training too? Do you know what might be the cause of this problem? Thanks a lot in advance.

**Comment by Kait0** [comment]
You set the root_dir to a folder called model.
This variable should point to the root dir of the dataset.
--logdir is the option for the folder where the models are saved.

**Comment by JianLiMech** [comment]
Than you for pointing it out! I will close this issue!
