### ISSUE TITLE
Branch 2021 Dataset Download Error

### ISSUE THREAD

**Issue by jimmyfyx** [autonomousvision/transfuser#156]
Dear Authors,

When we were trying to download the dataset from the 2021 branch, we met an unexpected error as below:
![error_403](https://user-images.githubusercontent.com/99617468/232644198-2c77eadd-f20d-48c3-8b79-1ab6e0a41cb4.png)
We have successfully downloaded the data for the first four towns, but failed to download the data starting from Town05. As you see in the screenshot, after encountering the error when running `./download_data.sh`, we directly copy the command in the .sh file and run it in the terminal, but the error still exists.

I wonder is there any solution for this issue? Thanks so much!

**Comment by kashyap7x** [comment]
Could you try again? Both https://s3.eu-central-1.amazonaws.com/avg-projects/transfuser/data/clear_weather_data/Town05.zip and https://s3.eu-central-1.amazonaws.com/avg-projects/transfuser/data/14_weathers_data/Town05.zip are currently working for me. It might have been a temporary AWS outage.

**Comment by jimmyfyx** [comment]
Thanks for the reply! I think it works now
