### ISSUE TITLE
branch 2021 model training error

### ISSUE THREAD

**Issue by jimmyfyx** [autonomousvision/transfuser#158]
Dear Authors,

When we try to train the model on the downloaded dataset, we constantly encounter this error. We are confused about the file path error because we have already changed the `root_dir` variable to a local directory in `config.py` for every model. It seems that the dataset can load files correctly but there is something wrong with PIL.

Thanks so much for the reply!

![Screenshot from 2023-04-22 15-37-26](https://user-images.githubusercontent.com/99617468/233805645-813a63d6-cf1f-4c60-ba48-eb7ba9fad9be.png)

**Comment by Kait0** [comment]
hm /is/rg/avg... is a path on our system. Somewhere it must be still hardcoded in the code.
You can debug to see where it comes from and replace it with your paths.
