### ISSUE TITLE
about evaluation issues

### ISSUE THREAD

**Issue by jun-ja** [autonomousvision/transfuser#16]
Hi, I got some issues during evaluation.

1. I got 'list index out of range' error in 'Loading the world'. How can I solve it?
![Screenshot from 2021-09-08 18-33-24](https://user-images.githubusercontent.com/81124797/132485321-459ea400-2d2f-495f-8614-d902edb55b7a.png)

2. I have often witnessed that vehicles around the ego vehicle sometimes stop without moving and end without proceeding. It seems to occur mainly in the right turn lane. I think this is not a matter of training, but an auto pilot algorithm problem for around vehicles. How can I solve this problem?

This is an example picture of the vehicle stopping and not moving.
![Screenshot from 2021-09-08 18-30-58](https://user-images.githubusercontent.com/81124797/132486315-2f1329a0-4ada-4b85-8cd2-be2b83494f0c.png)

Thank you.

**Comment by ap229997** [comment]
1. This occurs when the spawn position of a scenario is already occupied by another agent or a previously spawned scenario. In case of dense urban settings, this can happen a few times. This is not something you should concern with as long as most of the scenarios are getting spawned and only a few are getting skipped. If you really want to avoid this error altogether then you'll have to set the spawn locations in the json scenarios file such that each unique spawn location has only one possible scenario and none of the spawn locations overlap with spawn locations of vehicles.

2. I have also seen cases where vehicles sometimes just get stuck and don't move but I don't think that happens many times. I don't have a solution for this but you'd need to check the traffic manager in CARLA that handles the behavior of other agents and scenarios.

**Comment by jun-ja** [comment]
Thank you for your answer!
