### ISSUE TITLE
How can I view the BEV  and point cloud

### ISSUE THREAD

**Issue by QingZhuanya** [autonomousvision/transfuser#161]
good work!
But how can I view the top-down view and point cloud of vehicles as well as its trajectories in the evaluation dataset?
like [this:](https://www.bilibili.com/video/BV19W4y1q7nm/?spm_id_from=333.788.recommend_more_video.8&vd_source=9011820b8f246d5c448e55fdf5f996a6)

**Comment by Kait0** [comment]
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L935
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L719
Set the debug flag and a SAVE_PATH

**Comment by QingZhuanya** [comment]
Is that using in training time? Could Pre-training model show this  in Evaluation?

**Comment by Kait0** [comment]
forward_ego is used during evaluation
https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/submission_agent.py#L297

**Comment by QingZhuanya** [comment]
thanks!I will test it tomorrow!

**Comment by QingZhuanya** [comment]
I have run local_evaluation.sh，but Carla still only has a top-down view.
like this:
![lighttrfficcorner](https://user-images.githubusercontent.com/86774790/236602570-1563ddf1-d0c5-411c-a41e-1a8626d36d1c.png)
How can I display the point cloud and camera image in carla during evaluation?
And how can I real-time display waypoints?

**Comment by Kait0** [comment]
The visualizations get stored on the disk as images at the location that you need to specify via the
 SAVE_PATH environment variable.
 The code doesn't support real time preview of the visualizations.
 You could probably implement it yourself, by visualizing the images with matplotlib / pygame instead of saving them to the disk.

**Comment by QingZhuanya** [comment]
I see and thank for your excellent work
