### ISSUE TITLE
Prediction Visualizing

### ISSUE THREAD

**Issue by JianLiMech** [autonomousvision/transfuser#165]
Hi, thanks for your great work!

I have tried the transfuser, and it works perfectly.

But I have a problem, how can I visualize the predictions like the gif image in transfuser github?
![image](https://github.com/autonomousvision/transfuser/assets/105591726/43bea3d8-987b-402a-a1ee-1b299bdafed7)

Looking forward to seeing your reply! Thanks again!

**Comment by Kait0** [comment]
This particular video was cut together with a video editing software.
The individual components you can generate with https://github.com/autonomousvision/transfuser/blob/337957f9095a296aa7ab2ff1cea16eecca011848/team_code_transfuser/model.py#L935

You can look at 
https://github.com/autonomousvision/transfuser/blob/337957f9095a296aa7ab2ff1cea16eecca011848/team_code_transfuser/submission_agent.py#L297
to see how it is used.
