### ISSUE TITLE
About Predictions

### ISSUE THREAD

**Issue by ChaselWan** [autonomousvision/transfuser#167]
Hello!Thanks for your works! 
It's kinda easy,but how can I see the 2D predictions and BEV predictions?
I ran the `run_evaluation.sh` but predictions didn't appear.
Looking for your reply!Thanks again!

**Comment by Kait0** [comment]
See https://github.com/autonomousvision/transfuser/issues/165#issuecomment-1561030660

**Comment by ChaselWan** [comment]
thanks！Another question is how I can visualize Attention Map like Figure1 and Figure3 in your paper?

**Comment by Kait0** [comment]
https://github.com/autonomousvision/transfuser/issues/18
