### ISSUE TITLE
About data generation

### ISSUE THREAD

**Issue by XiangTodayEatsWhat** [autonomousvision/transfuser#17]
Hello! I have some problems about the data generation.
My operation process is：
1. Running CARLA Server
![image](https://user-images.githubusercontent.com/44435460/134628544-893e9e80-b214-4e2e-9d64-b78da9c48b1c.png)
2. ./leaderboard/scripts/run_evaluation.sh
![image](https://user-images.githubusercontent.com/44435460/134628725-fff80588-2977-43d1-b253-24c7a5b82cd2.png)
This seems that data generation is not successful. I would like to ask if the above operation is correct, and what should I do if there is a problem. 
And I understand that some images should be generated in the end, where will they be stored?
I would be very grateful if you could reply.

**Comment by ap229997** [comment]
The evaluation statistics indicate that the agent has completed the route which means that the data generation is working fine. The data is stored at the location assigned to `SAVE_PATH` in [leaderboard/scripts/run_evaluation.sh](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh).

**Comment by v413945333** [comment]
Thanks for your quick reply! According to your reply, I have found the generated images. They look different from the downloaded data in structure, but it probably doesn't matter.. Thank you again sincerely!

**Comment by ap229997** [comment]
Can you the difference in structure in the downloaded and generated images? Is it just the directory names or anything else too?

**Comment by elegentbamboo** [comment]
> Can you tell the difference in structure in the downloaded and generated data? Is it just the directory names or anything else too?
My generated data has only one extra *semantic_lidar* directory compared to the structure of *14_weathers_data* as you described.

**Comment by ap229997** [comment]
That's fine. I later added the functionality of semantic lidar in the data generation script.

**Comment by v413945333** [comment]
Sorry for the late reply, you are right. It is just the difference in directory names.

**Comment by ZKL-VOILET** [comment]
Hello! I have some problems about the data generation.
![image](https://user-images.githubusercontent.com/56717113/142345468-8c95b8af-5dd8-44d6-af70-f5e4344bbc52.png)

**Comment by ap229997** [comment]
From the error, it seems like the CARLA server cannot bind to port 2000 since it is already in use. Can you verify if the port is available or not?

**Comment by ZKL-VOILET** [comment]
> From the error, it seems like the CARLA server cannot bind to port 2000 since it is already in use. Can you verify if the port is available or not?

Thanks for your reply. I have changed the port to 8000, but it stuck here for half an hour. Dose it work?
![image](https://user-images.githubusercontent.com/56717113/142369050-07cffec6-6b06-472e-a20d-8cbc48e9c8fd.png)

**Comment by ap229997** [comment]
This message is normal, the server should be running now. You can try connecting a Carla client to the server and verify.

**Comment by Kin-Zhang** [comment]
Hi I found that about the data generation agent, did you find it not so correct also about the npc_agent:
I tried this scenario and find things interesting:

![image](https://user-images.githubusercontent.com/35365764/148788044-c5b601b7-2f67-42fe-b743-debc0749aafb.png)
![image](https://user-images.githubusercontent.com/35365764/148788116-954e84ee-c023-4246-823b-321406832c0e.png)

Like here the auto_agent and npc_agent will have collision and I notice there are many collision test fail on Town03, did you find that maybe a reason for the agent cannot avoid this kind of case?

It just my personal find out, since I tried to do some things more based on this repo.

**Comment by ap229997** [comment]
I did not experiment with the npc_agent so I don't know about its failure cases.

Regarding our autopilot, I am aware that it collides a few times. This is because our autopilot uses several heuristics for collision avoidance which has certain blindspots.

**Comment by Kin-Zhang** [comment]
> I did not experiment with the npc_agent so I don't know about its failure cases.
> 
> Regarding our autopilot, I am aware that it collides a few times. This is because our autopilot uses several heuristics for collision avoidance which has certain blindspots.

Thanks for the quick reply! I see.
Thanks again.

**Comment by Kin-Zhang** [comment]
> thanks for the quick reply! I see.
> Thanks again.

finally, I got the reason since I carefully see how our expert works and notice it didn't consider the change lane things so, the expert agent in this repo have a poor result score on Town03 which has many change lane action in routes.
