### ISSUE TITLE
How to get the LiDAR BEV view?

### ISSUE THREAD

**Issue by JianLiMech** [autonomousvision/transfuser#173]
Hello, thanks for your great work!

I would like to ask that is there any way to get the LiDAR BEV image? How do you view your lidar and rgb besides the debug mode? It would be a great help if you could answer :)

**Comment by Kait0** [comment]
What do you mean besides the debug view?
We use the debug view to see the lidar and camera.
If you want a different visualization you need to make it yourself.
You can find it the code [here ](https://github.com/autonomousvision/transfuser/blob/337957f9095a296aa7ab2ff1cea16eecca011848/team_code_transfuser/model.py#L935)

**Comment by JianLiMech** [comment]
Thanks for your quick reply. 
I will close this issue now. :)
