### ISSUE TITLE
Lane change

### ISSUE THREAD

**Issue by a1wj1** [autonomousvision/transfuser#178]
![1689662040323](https://github.com/autonomousvision/transfuser/assets/38905689/c2cc01fb-2539-4646-8a12-5f91a557f3d6)

May I ask if there are corresponding XML and JSON files for this scenario for testing on the leaderboard

**Comment by Kait0** [comment]
Think that was [route 32](https://github.com/autonomousvision/transfuser/blob/2022/leaderboard/data/longest6/longest6_split/longest_weathers_32.xml).
[This](https://github.com/autonomousvision/transfuser/blob/2022/leaderboard/data/longest6/eval_scenarios.json) is the json file.

**Comment by a1wj1** [comment]
Thank you!
