### ISSUE TITLE
scenarios

### ISSUE THREAD

**Issue by a1wj1** [autonomousvision/transfuser#182]
![1690188528106](https://github.com/autonomousvision/transfuser/assets/38905689/8815ee5c-a8d3-4e4d-a958-404aeb73d1b0)

Are these scenario settings set by oneself when collecting data, or are they the official route scenario settings provided for each town?

**Comment by Kait0** [comment]
There are no official route scenario settings.
Intel released a couple of different scenario files. 
We use one of them for the evaluation on longest6.
The scenarios used during training were created by ourselfs automatically see [here](https://github.com/autonomousvision/transfuser/tree/2022/tools/dataset).
