### ISSUE TITLE
leaderboard

### ISSUE THREAD

**Issue by a1wj1** [autonomousvision/transfuser#192]
Hello, may I ask which xml file is the score for uploading the leaderboard list? is: leaderboard/data/official/routes_testing.xml? right?

**Comment by Kait0** [comment]
The leaderboard file and towns are not publicly available.
You can find more information about the CARLA leaderboard [here](https://leaderboard.carla.org/).
Currently the version 1 leaderboard used in this paper is closed for submissions until the version 2 challenge is done.
