### ISSUE TITLE
Visualize 2D prediction and BEV prediction during evaluation

### ISSUE THREAD

**Issue by MaiRajborirug** [autonomousvision/transfuser#197]
![image](https://github.com/autonomousvision/transfuser/assets/54995188/3fde0e7a-9a60-4622-a981-f0f93eebfb8c)

Could you show what to change in the evaluation code to visualize 2D prediction and BEV prediction above? Thank you so much

**Comment by Kait0** [comment]
See https://github.com/autonomousvision/transfuser/issues/165

**Comment by MaiRajborirug** [comment]
Thank you so much for your timely response. I will close the issue now.
