### ISSUE TITLE
No such file or directory: 'results/sample_result.json'

### ISSUE THREAD

**Issue by coolCoco-MiMi** [autonomousvision/transfuser#2]
I ran the  " ./leaderboard/scripts/run_evaluation.sh" with the auto_pilot.py as agent.  And get the following error: 

![image](https://user-images.githubusercontent.com/56880104/115635204-2e1a2380-a2d9-11eb-9928-3177192a39f1.png)

I am not sure where and whether should I create the file?

**Comment by ap229997** [comment]
You need to make sure that the parent directory of the results file exists. In this case, you need to create a directory `results`.

**Comment by coolCoco-MiMi** [comment]
Ok! Thanks for your replying. I have solved the problem by creating a "results" directory.
