### ISSUE TITLE
Problem when run run_evaluation.sh

### ISSUE THREAD

**Issue by wanhaodong98** [autonomousvision/transfuser#20]
I change agent = transfuser_ agent and agent_ config=best_ model.pth you provided, but the following error occurred. According to the prompt, the torch version should be too low. I upgraded the torch version but reported another error.

Problem reading checkpoint. Route id 60 larger than maximum number of routes 32

========= Preparing RouteScenario_0 (repetition 0) =========
\> Setting up the agent

Could not set up the required agent:
\> version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f971843c193 in /home/harli/anaconda3/envs/transfuser/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f96cb7319eb in /home/harli/anaconda3/envs/transfuser/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f96cb732c04 in /home/harli/anaconda3/envs/transfuser/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c6536 (0x7f9713663536 in /home/harli/anaconda3/envs/transfuser/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295a74 (0x7f9713232a74 in /home/harli/anaconda3/envs/transfuser/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: _PyMethodDef_RawFastCallDict + 0x24c (0x5629eeae871c in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #6: _PyObject_FastCallDict + 0x6e (0x5629eeab8f5e in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #7: <unknown function> + 0x12f041 (0x5629eeace041 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #8: PyObject_Call + 0x66 (0x5629eeab97b6 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #9: <unknown function> + 0xc239e (0x5629eea6139e in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #10: _PyObject_FastCallKeywords + 0x54c (0x5629eeb1ec7c in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #11: <unknown function> + 0x1802d1 (0x5629eeb1f2d1 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x48a2 (0x5629eeb66602 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #13: _PyEval_EvalCodeWithName + 0x79e (0x5629eeab80de in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #14: _PyObject_FastCallDict + 0x312 (0x5629eeab9202 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #15: <unknown function> + 0x186bef (0x5629eeb25bef in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #16: _PyObject_FastCallKeywords + 0x54c (0x5629eeb1ec7c in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x47e5 (0x5629eeb66545 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x273 (0x5629eeab7bb3 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #19: _PyFunction_FastCallKeywords + 0x693 (0x5629eead8223 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #20: <unknown function> + 0x1800c5 (0x5629eeb1f0c5 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x48a2 (0x5629eeb66602 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #22: _PyFunction_FastCallKeywords + 0x187 (0x5629eead7d17 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #23: <unknown function> + 0x1800c5 (0x5629eeb1f0c5 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x621 (0x5629eeb62381 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #25: _PyObject_FastCallDict + 0x1b6 (0x5629eeab90a6 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #26: <unknown function> + 0x186bef (0x5629eeb25bef in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #27: _PyObject_FastCallKeywords + 0x54c (0x5629eeb1ec7c in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x47e5 (0x5629eeb66545 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #29: _PyFunction_FastCallKeywords + 0x187 (0x5629eead7d17 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #30: <unknown function> + 0x1800c5 (0x5629eeb1f0c5 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x621 (0x5629eeb62381 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #32: _PyFunction_FastCallKeywords + 0x187 (0x5629eead7d17 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #33: <unknown function> + 0x1800c5 (0x5629eeb1f0c5 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x621 (0x5629eeb62381 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0x187 (0x5629eead7d17 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x3f5 (0x5629eeb62155 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x273 (0x5629eeab7bb3 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #38: PyEval_EvalCode + 0x23 (0x5629eeab8ee3 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #39: <unknown function> + 0x227802 (0x5629eebc6802 in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #40: PyRun_FileExFlags + 0x9e (0x5629eebd094e in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #41: PyRun_SimpleFileExFlags + 0x1bb (0x5629eebd0b3b in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #42: <unknown function> + 0x232c3a (0x5629eebd1c3a in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #43: _Py_UnixMain + 0x3c (0x5629eebd1ccc in /home/harli/anaconda3/envs/transfuser/bin/python)
frame #44: __libc_start_main + 0xf3 (0x7f979e49c0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #45: <unknown function> + 0x1d7555 (0x5629eeb76555 in /home/harli/anaconda3/envs/transfuser/bin/python)

**Comment by wanhaodong98** [comment]
I use torch==1.4.0

**Comment by wanhaodong98** [comment]
I update torch==1.9.1 then


\> Registering the global statistics
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7fb41cdf0440>
Traceback (most recent call last):
  File "/home/harli/transfuser-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 124, in __del__
    self._cleanup()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 157, in _cleanup
    self._agent_watchdog.stop()
  File "/home/harli/transfuser-main/scenario_runner/srunner/scenariomanager/watchdog.py", line 72, in stop
    self._timer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

**Comment by ap229997** [comment]
I had updated the model checkpoint for transfuser earlier, which is trained on a newer version. Thanks for pointing this out, I'll update the dependencies.

Regarding the other error, try changing `CHECKPOINT_ENDPOINT` in [run_evaluation.sh](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh#L21). If the results file of an earlier finished evaluation of the same name already exists and `RESUME=True`, then this error could occur. Let me know if this works.

**Comment by wanhaodong98** [comment]
Thank for your reply, I have solved this problem.

**Comment by Kin-Zhang** [comment]
I also met this error, but directly change the pytorch version seems that the car didn't move. when torch==1.9.0 and run_evaluation.sh in docker.

**Comment by Kin-Zhang** [comment]
And I also test on the master branch with modify team_agent to transfuser and then run evaluation which I found the agent will not move on first task with some python warning?
![2021-12-17_20-05](https://user-images.githubusercontent.com/35365764/146544210-44deaa55-d873-45f7-88aa-819e49e54162.png)
But the success on the second task which is quite wried.
