### ISSUE TITLE
ego-vehivcle

### ISSUE THREAD

**Issue by No4x** [autonomousvision/transfuser#202]
> Detected agent being stuck. Move for frame:  0
> Detected agent being stuck. Move for frame:  1
> Detected agent being stuck. Move for frame:  2
> Detected agent being stuck. Move for frame:  3
> Detected agent being stuck. Move for frame:  4
> Detected agent being stuck. Move for frame:  5
> Detected agent being stuck. Move for frame:  6
> Detected agent being stuck. Move for frame:  7
> Detected agent being stuck. Move for frame:  8
> Detected agent being stuck. Move for frame:  9
> Detected agent being stuck. Move for frame:  10
> Detected agent being stuck. Move for frame:  11
> Detected agent being stuck. Move for frame:  12
> Detected agent being stuck. Move for frame:  13
> Detected agent being stuck. Move for frame:  14
> WARNING: attempting to destroy an actor that is already dead: Actor 3565 (vehicle.audi.tt)
> Destroying ego-vehicle!
> WARNING: attempting to destroy an actor that is already dead: Actor 3832 (vehicle.tesla.model3)
> Destroying ego-vehicle!
> WARNING: attempting to destroy an actor that is already dead: Actor 3833 (vehicle.audi.tt)
> Destroying ego-vehicle!
> Trying to remove a non-existing actor id 3565
> WARNING: attempting to destroy an actor that is already dead: Actor 3568 (vehicle.audi.tt)
> Destroying ego-vehicle!
> Trying to remove a non-existing actor id 3568
> Detected agent being stuck. Move for frame:  0
> Detected agent being stuck. Move for frame:  1
> Detected agent being stuck. Move for frame:  2
> Detected agent being stuck. Move for frame:  3
> Detected agent being stuck. Move for frame:  4
> Detected agent being stuck. Move for frame:  5
> Detected agent being stuck. Move for frame:  6
> Detected agent being stuck. Move for frame:  7
> Detected agent being stuck. Move for frame:  8
> Detected agent being stuck. Move for frame:  9
> Detected agent being stuck. Move for frame:  10
> Detected agent being stuck. Move for frame:  11
> Detected agent being stuck. Move for frame:  12
> Detected agent being stuck. Move for frame:  13
> Detected agent being stuck. Move for frame:  14
> 
> Error during the simulation:
> > trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
> 
> Traceback (most recent call last):
>   File "/home/zizhen/work/TransFuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 352, in _load_and_run_scenario
>     self.manager.run_scenario()
>   File "/home/zizhen/work/TransFuser/leaderboard/leaderboard/scenarios/scenario_manager_local.py", line 136, in run_scenario
>     self._tick_scenario(timestamp)
>   File "/home/zizhen/work/TransFuser/leaderboard/leaderboard/scenarios/scenario_manager_local.py", line 164, in _tick_scenario
>     self.scenario_tree.tick_once()
>   File "/home/zizhen/.conda/envs/transfuser/lib/python3.7/site-packages/py_trees/behaviour.py", line 158, in tick_once
>     for unused in self.tick():
>   File "/home/zizhen/.conda/envs/transfuser/lib/python3.7/site-packages/py_trees/composites.py", line 578, in tick
>     for node in child.tick():
>   File "/home/zizhen/.conda/envs/transfuser/lib/python3.7/site-packages/py_trees/composites.py", line 578, in tick
>     for node in child.tick():
>   File "/home/zizhen/.conda/envs/transfuser/lib/python3.7/site-packages/py_trees/behaviour.py", line 249, in tick
>     new_status = self.update()
>   File "/home/zizhen/work/TransFuser/scenario_runner/srunner/scenariomanager/scenarioatomics/atomic_criteria_local.py", line 2000, in update
>     location = self._actor.get_location()
> RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.
> > Stopping the route
> Resetting ego-vehicle!

Hi, I encountered this issue. I can't find the code where the ego-vehicle is destroyed or reset. Could you help me?

**Comment by Kait0** [comment]
I think the ego vehicle gets created [here](https://github.com/autonomousvision/transfuser/blob/22b3ccdb7e806b42c9be2aa476b71546e8ec3620/leaderboard/leaderboard/scenarios/route_scenario_local.py#L250).

**Comment by No4x** [comment]
Thanks
