### ISSUE TITLE
Need some help about understanding the code

### ISSUE THREAD

**Issue by Oliverwang11** [autonomousvision/transfuser#203]
Hi, 

Thanks again for your contribution!

After reading the paper, I took a look at the code, especially for the GPT class, but I found something I am a little bit confused about. 

1. In the paper, it says that the input image is down-sampled to 5x22xC and LiDAR to 8x8xC. If I understand correctly, for inference batch size, in your comments B, should be one? And why the input size of the image is Bx4xseq_len, C, H, W in your comments, where does the number 4 come from? Maybe I misunderstood something.

`    def forward(self, image_tensor, lidar_tensor, velocity):
        """
        Args:
            image_tensor (tensor): B*4*seq_len, C, H, W
            lidar_tensor (tensor): B*seq_len, C, H, W
            velocity (tensor): ego-velocity
        """
`

Best wishes!
Thanks again!

**Comment by Kait0** [comment]
I think it's just a typo.

**Comment by Oliverwang11** [comment]
Thanks for your reply, so the batch size, B, during inference is one right?

**Comment by Kait0** [comment]
yes

**Comment by Oliverwang11** [comment]
Thanks a lot!
