### ISSUE TITLE
cvpr2021 model training error

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#207]
Hello,

With similar to the https://github.com/autonomousvision/transfuser/issues/158#issue-1679710037 issue, I am trying to run the model in HPC and facing the error in loading .npy file for various models,

Transfuser model: (in Town03)
![transfuser](https://github.com/autonomousvision/transfuser/assets/114591814/10f9fc81-fc39-4e90-81d8-3c935fcb425d)

Geometric fusion: (in Town03)
![geo_fusion](https://github.com/autonomousvision/transfuser/assets/114591814/c9317559-5347-424b-8630-35e305c428b7)

cilrs: (in Town04)
![cilrs](https://github.com/autonomousvision/transfuser/assets/114591814/89283740-aec9-499c-a61c-f6da81755b9a)

I am using Minimal Dataset to train the model. I also changed the root_dir variable to a local directory in config.py for all the models.

Please help me to resolve the issue.

Thanks.

**Comment by ap229997** [comment]
This generally occurs if the file you are trying to open and load is empty, can you check if the file exists and try to load it independently
