### ISSUE TITLE
Dependencies error to train the transfuser model

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#208]
Hi,

As discussed in https://github.com/autonomousvision/transfuser/issues/114#issue-1406818291, I installed the necessary dependencies for the conda environment. But when I train the model, I face the following error, please help to resolve and guide me to train the model.  
![image](https://github.com/autonomousvision/transfuser/assets/114591814/e0a5619c-11e2-4500-9595-a4b86c84c7f9)
Thanks in advance.

**Comment by Kait0** [comment]
You can just comment [this line](https://github.com/autonomousvision/transfuser/blob/22b3ccdb7e806b42c9be2aa476b71546e8ec3620/team_code_transfuser/model.py#L11C26-L11C40).
Its just for an ablation (you likely don't need it) but unfortunately introduces tricky cuda dependencies.

**Comment by SRajasekar333** [comment]
Hi,
Thanks for the reply.
Yes I corrected the code and trained the model, but now I face error in Multiprocessing.
![image](https://github.com/autonomousvision/transfuser/assets/114591814/33a15efc-caf5-4934-9c4c-a06f8bd7e509)
Could you please help me, due to what reason I face this error and how to troubleshoot it?
Thanks in advance.

**Comment by Kait0** [comment]
This might not actually be an error with multiprocessing. The start method of... message is normal info printing.
You need to debug line by line, either with prints or a debugger to see where exactly the code crashes / gets killed by the os.
