### ISSUE TITLE
Problem about evaluation

### ISSUE THREAD

**Issue by wanhaodong98** [autonomousvision/transfuser#21]
When I was running the model you provided, I encountered many times that the autonomous vehicle was stationary. I want to know what caused this. The following is the simulation result. The timeout is caused by the vehicle stopping.
https://drive.google.com/file/d/13SiSpYUFG0jfKtFWhHFKHSj0V9TLaemB/view?usp=sharing

**Comment by Kin-Zhang** [comment]
Oh! Finally I found some one also notice the lastest model checkpoint have this problem! I think it's quite serious, escpecially you just run it at your computer, here is a picture from the running:
![2021-12-17_20-28](https://user-images.githubusercontent.com/35365764/146544753-33fd3e34-6076-4b5d-baac-bf4131d7fdb7.png)

**Comment by ap229997** [comment]
We are aware of this issue and we currently don't have a good solution for it.

**Comment by FitashUlHaq** [comment]
any update on this? :)

**Comment by Kait0** [comment]
The controller creeping described in the extended paper is a useful workaround to this problem.
https://arxiv.org/pdf/2205.15997.pdf
If you slightly force the model to creep forward it will usually start driving again, if there is no causal reason to stop.

**Comment by Hither1** [comment]
> The controller creeping described in the extended paper is a useful workaround to this problem. https://arxiv.org/pdf/2205.15997.pdf If you slightly force the model to creep forward it will usually start driving again, if there is no causal reason to stop.

Hi Just want to clarify this is not implemented in the current git repo code right?

**Comment by Kait0** [comment]
We have released the code last week in the [2022 branch](https://github.com/autonomousvision/transfuser/tree/2022) of the github.
You can find it in team_code_latest/submission_agent.py
