### ISSUE TITLE
Dataset for evaluation 

### ISSUE THREAD

**Issue by MCUBE-2023** [autonomousvision/transfuser#213]
First of all, Thank you for your amazing work!

![transfuser](https://github.com/autonomousvision/transfuser/assets/122301027/839a4a05-1a7b-440f-add4-250070055e47)

Based on my understanding, there are 2 ways to run the transfuser model (and please correct me if I am wrong):
1- Whether by generating the training files.
2- Or by using directly the pretrained files that you provide in the transfuser github.

For the 2nd scenario (in case if using directly the pretrained files), do I still need to download the dataset (210 GB) (please see the screenshot) to evaluate an agent, or can I directly evaluate the model without downloading this dataset  ?
Particularly to run this instruction: ./leaderboard/scripts/local_evaluation.sh <carla root> <working directory of this repo (*/transfuser/)>

**Comment by Kait0** [comment]
No you don't need to download the dataset to evaluate the pre-trained models, just the [model checkpoints](https://github.com/autonomousvision/transfuser?tab=readme-ov-file#pretrained-agents) themselves.

**Comment by MCUBE-2023** [comment]
Thank you so much for your quick reply!
