### ISSUE TITLE
my vehicle remains stationary all the time

### ISSUE THREAD

**Issue by zygalaxy** [autonomousvision/transfuser#214]
When I run the pre-training model, my vehicle remains stationary all the time. How can I solve it?

**Comment by Kait0** [comment]
Which branch are you using? On the 2021 branch this is expected (should not happen always but can happen in multiple routes).
This is an instance of causal confusion/ Inertia Problem and the model in the 2021 is strongly affected by it.
The newer models in the 2022 branch are better and have this problems less (but still do). 
The 2022 branch additionally has a creeping rule to posthoc fix this problem. 
We noticed that causal confusion is not robust and can easily be broken if the vehicle slowly roles forward, which we do if the car is stuck for a long time (e.g.: see Table 10 in the paper).

**Comment by zygalaxy** [comment]
Thank you for your quick and accurate answer. I used the branch in 2022. The vehicle remains stationary all the time, only occasionally moving a little to the right and front. So can this be solved?

**Comment by zygalaxy** [comment]
Thank you for your quick and accurate answer. I use the 2022 version. The vehicle remains stationary all the time, only occasionally moving a little to the right and front. Can this be solved?

**Comment by zygalaxy** [comment]
I tried: 1) using -vulkan to solve this problem, but I can only use -oepngl, but I can't use -vulkan. Once I use -vulkan, carla0.9.10.1 can't display the picture. 2) I also tried -quality-level=Low, but the vehicle never moves.

**Comment by Kait0** [comment]
opengl is fine. This sounds more like a problem with the setup then.
My first guess is that the model weights aren't loaded correctly (this can fail silently and use uninitialized weights).
Thy debugging this [here](https://github.com/autonomousvision/transfuser/blob/b602efac325e77f853460ba0d79dc364c2c70488/team_code_transfuser/submission_agent.py#L96).

**Comment by zygalaxy** [comment]
Thank you for your patient answer. I debugged the place you pointed out. With temp = net. load _ state _ dict (state _ dict, strict = false), I got temp = _ incorporable keys (missing _ keys = [], unexpected _ keys = ['_ model. lidar _ encoder. _ model. stem.conv.weight'. Does this mean that the model does not load weights normally?

**Comment by zygalaxy** [comment]
Thank you for your patience in answering. I debugged the areas you pointed out. Through `temp = net.load_state_dict(state_dict, strict=False)`, 1) For `transfuser`, I got `temp = _IncompatibleKeys(missing_keys=[], unexpected_keys=['_model.lidar_encoder._model.stem.conv.weight'])`. 2) For `late_fusion`, I got `temp=<All keys matched successfully>`, does this mean that the weights have been loaded correctly, but in both cases, the vehicle remains stationary! I'm very distressed about this issue.

**Comment by Kait0** [comment]
These should be fine, these keys are mismatched because the models were trained with an older codebase.
Can you try the [visualization function](https://github.com/autonomousvision/transfuser/blob/b602efac325e77f853460ba0d79dc364c2c70488/team_code_transfuser/model.py#L936) and send an example here?
You will know that the model weights are loaded correctly if those look reasonable.

You need to set the environment variable SAVE_PATH=/path/to/log/folder
as well as put the debug variable to True in the [config](https://github.com/autonomousvision/transfuser/blob/b602efac325e77f853460ba0d79dc364c2c70488/team_code_transfuser/config.py#L35C1-L35C24).
to use the visualization function.

**Comment by zygalaxy** [comment]
The global position of the vehicle is shown in Figure 1.
![2024-05-23 10-00-03屏幕截图](https://github.com/autonomousvision/transfuser/assets/139957236/9c824921-c2f3-4c11-8f81-8edc0f383c2c)
The result of visualization is occasionally Figure 2 and Figure 3, but the position of the vehicle remains unchanged all the time.
![482](https://github.com/autonomousvision/transfuser/assets/139957236/a48dea20-f9cc-4d7a-9eca-79b8e1db2a7f)
![563](https://github.com/autonomousvision/transfuser/assets/139957236/7714ca10-1c52-407d-acb4-27237c339334)

It seems that it is because the white block in the middle affects the vehicle's progress.

**Comment by Kait0** [comment]
Hm that is very strange. It means the central camera is failing occasionally.
This should not happen. I have never seen this before, you need to debug to see why this is happening.
In general how the camera image is created, is by having 3 high resolution cameras, cropping out the center part (to remove image distortions) and then concatenating them together.

It is expected that the vehicle doesn't move if the vehicle breaks every couple frames. You need to throttle a lot of frames consecutively in CARLA for the car to start driving.

The model itself seems to be loaded correctly.

**Comment by zygalaxy** [comment]
I found that the white block in the middle was only an accidental phenomenon. I collected the visualization results twice again and found no white block in the middle, but the vehicle never moved!

**Comment by Kait0** [comment]
The white bar is not just because of the visualization as it also shows up in the model prediction (e.g. depth map), but perhaps its rare?

In the example you showed above the stuck detector is true, so the vehicle should be forced to move forward if the code is working correctly.
Does the model itself predict that it should move?
Did you test different routes?

**Comment by zygalaxy** [comment]
Thank you for your patient answer. I will try again.
