### ISSUE TITLE
weather changes every 3s on average

### ISSUE THREAD

**Issue by zygalaxy** [autonomousvision/transfuser#217]
When I am running./leaderboard/scripts/datagen.sh, the weather changes every 3s on average. Is this normal?

**Comment by Kait0** [comment]
Yes, this is intentional for data augmentation.
The relevant code is [here](https://github.com/autonomousvision/transfuser/blob/b602efac325e77f853460ba0d79dc364c2c70488/team_code_autopilot/data_agent.py#L222).

**Comment by zygalaxy** [comment]
Thank you very much, I will close the question.
