### ISSUE TITLE
How to interpret data?

### ISSUE THREAD

**Issue by jun-ja** [autonomousvision/transfuser#22]
Hello, I want to know how to interpret 2d_bbs and 3d_bbs.

I see that lidar can be reshaped to (-1,4), but I wonder how 2d_bbs and 3d_bbs should be converted and how they should be interpreted.

Thank you!

**Comment by ap229997** [comment]
You can refer to the function `_draw_2d_bbs` in [base_agent.py](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/team_code/base_agent.py). For interpreting 3d_bbs, one way could be to project them into 2D image and visualze them. The functions `_find_obstacle_3dbb`, `_get_2d_bb_baseline` and `_baseline_to_box` can provide more details.
