### ISSUE TITLE
'AttributeError' and 'UnboundLocalError' when running local_evaluation.sh

### ISSUE THREAD

**Issue by rogerfinnerty** [autonomousvision/transfuser#222]
Hello, 

I'm trying to run the local evaluation script and am getting the following errors:

![Screenshot from 2024-05-30 11-38-12](https://github.com/autonomousvision/transfuser/assets/122404055/b7a5144b-bf2e-4241-ba79-70295e3b91c2)

I've set up the environment and am running a Carla instance, I've also changed the paths in the shell script ... how can I fix this?

Thanks!

**Comment by Kait0** [comment]
You need to send the entire stacktrace. This is a secondary error. The real problem likely came earlier.

**Comment by rogerfinnerty** [comment]
Apologies, here is the rest of the stack trace
![image](https://github.com/autonomousvision/transfuser/assets/122404055/cfa375ab-f6ef-4bf2-add7-310e75c2287e)

**Comment by Kait0** [comment]
That means the torch_scatter module didn't install correctly.
The easy workaround is to just comment out [this line](https://github.com/autonomousvision/transfuser/blob/b602efac325e77f853460ba0d79dc364c2c70488/team_code_transfuser/model.py#L11), you will likely not need it.
