### ISSUE TITLE
How to autogenerate route viz on maps

### ISSUE THREAD

**Issue by ajdroid** [autonomousvision/transfuser#223]
Hi, thanks for your work in this area -- super useful!
I'm wondering if you could point me to the code for generating route annotated maps like in the [longest6 description page](https://github.com/autonomousvision/transfuser/tree/2022/leaderboard/data/longest6) here.

Thanks!

**Comment by Kait0** [comment]
https://github.com/autonomousvision/transfuser/tree/2022/tools/dataset
