### ISSUE TITLE
[Evaluation issue] Depth, Semantic image output issues and vehicle stopping

### ISSUE THREAD

**Issue by garong** [autonomousvision/transfuser#226]
Thank you for providing the paper and code.

I have issues. Despite using pre-trained models, Ego vehicles do not move properly, often moving off the road or stalling.

So I have seen several posts discussing these issues and have activated visualization by adding the SAVE_PATH environment variable during the vehicle evaluation process.
- my gpu is nvidia titan rtx(24GB)
- (#135)
- (#128)
-  ...

I confirmed the following problem.
HD Map, Depth, and Semantic segmentation images are output as follows.
![Issue](https://github.com/autonomousvision/transfuser/assets/6006221/9fb65ee7-2176-4c8c-beea-fa659d07a4ed)

I would like to inquire whether these issues are causing the vehicle not to move properly.

**Comment by Kait0** [comment]
Looks like the models were not loaded properly. 
What path did you set for loading, and which files were in them?

**Comment by garong** [comment]
Thank you so much for your response. The model path and its contents you mentioned are as follows:
path : /home/tops/sschai/transfuser/model_ckpt/models_2022/transfuser/   and there are 4 files (args.txt, model_Seed1_39.pth, model_seed2_39.pth, model_seed_3_37,pth)  

Additionally, I share the parts I modified and some of the paths.

![image](https://github.com/autonomousvision/transfuser/assets/6006221/61d6d29e-5c2d-4902-b225-5d4f06978938)

**Comment by Kait0** [comment]
hm I don't see an obvious issue.
You need to debug [here](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/submission_agent.py#L87) to check whether the model is loaded correctly.

**Comment by garong** [comment]
As you pointed out, there was an issue with that variable. It seems that things got tangled up during code analysis. The problem has been resolved. 

I appreciate your kind and helpful response and want to thank you once again from the bottom of my heart.
