### ISSUE TITLE
Accessing the gradient of the transfuser model in evaluation mode

### ISSUE THREAD

**Issue by MCUBE-2023** [autonomousvision/transfuser#227]
Hi, 

Would please tell me which part of the code allows me to access the gradient of the transfuser model in evaluation mode ?

Thank you bunches in advance :)

**Comment by Kait0** [comment]
If you mean gradients during deployment, than you need to look at the [run_step](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/submission_agent.py#L236) function.
Gradient computation is disabled by default to improve efficiency, you need to remove the inference_mode() and no_grad() decorators.

**Comment by MCUBE-2023** [comment]
Thank you so much for your quick reply. Your help allowed me to resolve an issue in which I've been blocked for more than one month. I acknowledge your highly developed professional qualities :)
