### ISSUE TITLE
how to visualize the topdown image ?

### ISSUE THREAD

**Issue by MCUBE-2023** [autonomousvision/transfuser#229]
![image](https://github.com/user-attachments/assets/b531dd4e-5591-4304-a1c1-0985b4b1a1d8)

Assuming the attached image is a topdown image (please correct me if I am wrong). What is the name of this image in the code ? And would you please point out where exactly in the code I can plot it or save it to the disk ?

**Comment by Kait0** [comment]
This looks like a screenshot of a CARLA server. Just run CARLA on a computer with a monitor and make a screenshot.
There is no code for this in this codebase. You could write one yourself by saving the spectator camera or a set a camera high up that looks down.

We have a visualization function [here](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/model.py#L726) in the code but it will produce a different result.

**Comment by MCUBE-2023** [comment]
Alright, thank you for the quick reply :)
