### ISSUE TITLE
How to measure the affordances 'relative angle' and 'lateral distance' with respect to the waypoints

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#232]
Hello,

I am trying to extract the affordances from the `measurements.json` so please clarify,

1. How to measure the `relative_angle` between the vehicle's current direction and the direction of the waypoints target? 
from the `autopilot.py`, I found the angle defined as https://github.com/autonomousvision/transfuser/blob/fe05003765294d82f03977da40767467eca53261/team_code_autopilot/autopilot.py#L1118
so is this the relative_angle which is stored as `measurements[angle] ` in the .json file?, please clarify.

2. How to measure the `lateral_distance` from the vehicle position to the centerline defined by the waypoints, using the measurements data?

Please provide a solution.

Regards.

**Comment by Kait0** [comment]
1. The data is stored [here](https://github.com/autonomousvision/transfuser/blob/fe05003765294d82f03977da40767467eca53261/team_code_autopilot/autopilot.py#L321). The angle is normalized, so you might need to unnormalize before using it.

2. You need to convert the ego vehicle center into the local coordinate system of the waypoint and then measure the absolute y value. We do not provide code for this you will need to write it yourself.

**Comment by SRajasekar333** [comment]
Hi @Kait0,

Thanks for the reply.

1. Could you please elaborate about the normalization of the angle, how should we `unnormalize` from the value that we get from the `measurements.json`

Regards!
