### ISSUE TITLE
How to measure the target_vehicle_distance from label_raw.json

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#234]
Hi,

I am trying to extract the `target_vehicle_distance `form the` label_raw.json`, but I am facing some issues to exactly find the target_vehicle_hazard from the `car_id` list, so please guide me on how to define the exact target vehicle hazard.

From **label_raw.json**, we could find that the `"Car_id"` which has the `"distance": -1` to be as the current `ego_vehicle`. and from **measurements.json** we could find the `vehicle_hazard: [True, False]` .

Now how to find the  `"target_Car_id"` from the label list which will be the potential target_vehicle_hazard (for e.g.. vehicle which lies in the same lane of the ego_vehicle and which lies infront of the ego_vehicle to be called as a potential hazard) and then to extract the corresponding `"distance":` of the car_id

Thanks!

**Comment by Kait0** [comment]
We don't store the information about which vehicle caused the hazard flag from the expert.
You could collect a new dataset and store that information.
The autopilot does not really have a notion of target_vehicle.
