### ISSUE TITLE
How to unnormalize the 'relative angle'  from the data.json

### ISSUE THREAD

**Issue by SRajasekar333** [autonomousvision/transfuser#235]
Hi @Kait0,

Thanks for the reply.

1. Could you please elaborate about the normalization of the angle, how should we `unnormalize` from the value that we get from the `measurements.json`

Regards!

_Originally posted in https://github.com/autonomousvision/transfuser/issues/232#issuecomment-2275226250_

**Comment by Kait0** [comment]
Just read through the code a bit. The relevant part is for example here.
https://github.com/autonomousvision/transfuser/blob/fe05003765294d82f03977da40767467eca53261/team_code_autopilot/autopilot.py#L401
