### ISSUE TITLE
Unable to recreate results by following the instructions given in the github Readme

### ISSUE THREAD

**Issue by akshay18iitg** [autonomousvision/transfuser#239]
I am facing issue with installing torch scatter with torch 0.11.0. Can anyone assist me with the problem

**Comment by suryajayaraman** [comment]
@akshay18iitg , by torch 0.11.0, do you mean torch 1.11 version or torchvision 0.12.0? Did you try creating a conda environment with the provided environment.yml file?

**Comment by akshay18iitg** [comment]
I mean torch 1.11. Ya. I created conda environment with provided environmnet.yml file. I also installed torch scatter and mmcv full as mentioned in the repo. But, I am facing issues with compatibility of torch scatter.

**Comment by suryajayaraman** [comment]
@akshay18iitg , did you try running the script? I remember seeing similar errors, but did not have issues running the model

**Comment by akshay18iitg** [comment]
@suryajayaraman , ya I tried running local evaluation script. But it gives an error related to torch scatter

**Comment by Kait0** [comment]
You can simply comment [this line](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/model.py#L11) and save yourself the hassle of compiling torch scatter (it sometimes compiles against your local cuda installation). It is only needed for a variation that you will likely not use.

**Comment by akshay18iitg** [comment]
@Kait0 . Ya. It works after commenting the line. Just want to confirm one more thing. The longest6 results shared in youtube video can be replicated using the given pretrained weights?

**Comment by Kait0** [comment]
yes

**Comment by akshay18iitg** [comment]
Thanks @Kait0 for resolving the issue.
