### ISSUE TITLE
Timeout signification and impact

### ISSUE THREAD

**Issue by MCUBE-2023** [autonomousvision/transfuser#245]
Hi, 
First of all, thank you for your receptivity and your quick answers to issues :)

Referring to leaderboard_evaluator_local.py (see the attached screen shot), and referring to this particular line of code: parser.add_argument ('--timeout', default="60.0", help='Set the CARLA client timeout value in seconds'), I have the following questions regarding the variable 'timeout':

1- What is the significance of the timeout variable? For instance, does the timeout relate to a case where the ego vehicle remains blocked without performing any action, and after the timeout period elapses, the code exits execution?

2- What is the impact of varying the value of the timeout variable? Specifically, how does increasing or decreasing this value affect the system’s behaviour?

![image](https://github.com/user-attachments/assets/28023c2a-9c07-4510-bbc0-854fa3ef6046)

**Comment by Kait0** [comment]
This timeout which is the client timeout has nothing to do with the agent timeout (which is not an argument).
This value is used by a watchdog to determined if the simulation has crashed.
If the simulation / code doesn't crash than increasing it has no effect. 
We sometimes set it higher on servers where CARLA takes a long time to start.
