### ISSUE TITLE
Some problems with the results of the local_evaluation.sh

### ISSUE THREAD

**Issue by WeiranJia** [autonomousvision/transfuser#255]
When I run the file local_evaluation.sh, I get some problems with the results, and the whole screenshots are shown below:
<img width="849" alt="result1" src="https://github.com/user-attachments/assets/6b82a237-d244-4a3d-bbaf-657948f6fb38">
<img width="851" alt="result2" src="https://github.com/user-attachments/assets/c23a8565-9cb8-4451-baad-f5f857da8642">
<img width="853" alt="result3" src="https://github.com/user-attachments/assets/b14a8071-62ca-40fd-9ce3-10db2254c57a">
<img width="854" alt="result4" src="https://github.com/user-attachments/assets/14593865-3b0c-4b2c-8092-bbceded77bc9">
<img width="849" alt="result5" src="https://github.com/user-attachments/assets/a8c4988f-e478-4c93-803a-e4092ad59195">
<img width="851" alt="result6" src="https://github.com/user-attachments/assets/cbfd8f6a-228f-4a5a-8582-8ef3915516bb">
<img width="851" alt="result7" src="https://github.com/user-attachments/assets/2708232f-a715-4db4-9b0f-033a7770a2b5">
<img width="851" alt="result8" src="https://github.com/user-attachments/assets/db9470be-93f3-4f49-98f6-7928d3d32596">
Could you please tell me whether the Results of RouteScenario_0 are right or not? and how can I solve the errors happening in the Preparing RouteScenario_1 part? Thank you a lot!

**Comment by Kait0** [comment]
The second error a sensor took too long is a usual crash where you just have to rerun the route. Maybe you can have a look [here](https://github.com/autonomousvision/transfuser/issues/216).

14 collisions on route 0 is too much though, so there is probably some problem.

**Comment by WeiranJia** [comment]
Thank you for your timely reply, and the second error "a sensor took too long" is solved after I rerun the route. For the problem that the number of collisions is too high which you mentioned, I reopen the visualization function and get the result shown below:
![1](https://github.com/user-attachments/assets/c817363c-8612-42a8-8ca5-af3e82955210)
I guess that the problem is the LiDAR image can not load normally, but could you please tell me how can I solve this problem? Thank you a lot!

**Comment by Kait0** [comment]
Yes that seems to be the problem. I don't know why it occurs. You need to debug [here](https://github.com/autonomousvision/transfuser/blob/3852e65e070f2efcfaba18fbbdb48057096b8a9e/team_code_transfuser/submission_agent.py#L211) and following to see where the LiDAR data gets lost.
