### ISSUE TITLE
Data Description

### ISSUE THREAD

**Issue by moon5ye** [autonomousvision/transfuser#29]
I am wondering whether we have a data description? Or can you describe what are command, x_command, y_command and theta in data.py?

Also, can you please provide the code that can regenerate the preload files? Because the preload files in the dataset folder used old pathes.

**Comment by ap229997** [comment]
x_command, y_command are the coordinates of the target point that the agent needs to follow and theta is the orientation of the ego-agent that is provided by the IMU. You can refer to [auto_pilot.py](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/team_code/auto_pilot.py) for more details into how these are computed.

For the preload files, you can simply delete the old files and the data loader will automatically generate new ones.

**Comment by moon5ye** [comment]
Thank you so much!
