### ISSUE TITLE
No module names cirl 

### ISSUE THREAD

**Issue by coolCoco-MiMi** [autonomousvision/transfuser#3]
Hi, could you please check if there is the "model_ckpt/cirls" file? I run the CIRLS agent and downloaded the model_ckpt file but there is no "cirls" under the file. 

![image](https://user-images.githubusercontent.com/56880104/115796792-75b7b280-a3a0-11eb-8826-d3a9acaa6159.png)

Also, this is the error information:
![image](https://user-images.githubusercontent.com/56880104/115797120-2756e380-a3a1-11eb-8831-dc7ec886b981.png)

Best
Thanks!

**Comment by ap229997** [comment]
The model checkpoint for CILRS is not uploaded yet, I'll upload it soon.

**Comment by coolCoco-MiMi** [comment]
I see. Thanks!

**Comment by Aditya183** [comment]
Hi,
Is this model supports Windows 10 ?
