### ISSUE TITLE
Traffic light in the image

### ISSUE THREAD

**Issue by WPH-commit** [autonomousvision/transfuser#30]
Thank you very much for sharing your great work and data. I generated some data using your script and I noticed that usually the traffic light in the image is very small (sometimes even hard for me to distinguish). Is it the common case or I have some wrong settings?

**Comment by ap229997** [comment]
That is usually the case and traffic light detection is a problem that I have noticed in the trained models. If you want to generate images with better visibility of traffic lights, you can try playing around with the camera sensor [attributes](https://carla.readthedocs.io/en/latest/ref_sensors/#rgb-camera).

**Comment by WPH-commit** [comment]
Thank you very much! But we can't set those advanced attributes of cameras for the carla leaderboard, right?

**Comment by ap229997** [comment]
I don't exactly know which all attributes can be set. You might want to check with the CARLA people for that. There's a CARLA discord which you can join and ask about it there.

**Comment by WPH-commit** [comment]
Hi, sorry to bother you again. But do you know what these yellow blocks are in the middle of the roads
![0024](https://user-images.githubusercontent.com/62696862/143521781-61f1a5b0-3a7c-4725-b8ff-e744e0667e06.png)
?

**Comment by ap229997** [comment]
The yellow blocks just in front of the ego vehicle represent some sort of dirt (consider it as an obstacle) on the road which is rendered as part of scenario 1.

**Comment by WPH-commit** [comment]
thank you
