### ISSUE TITLE
Problem in run evaluation for transfuser agent 

### ISSUE THREAD

**Issue by hlaahmed** [autonomousvision/transfuser#34]
I get this error 
![B3212EAE-E0CA-42B3-9B4B-C91D12CFB058](https://user-images.githubusercontent.com/40806663/144156610-b836bbfb-a2ff-42fe-b79b-c18c21ec5e8b.jpeg)

**Comment by ap229997** [comment]
From the error, it seems like you don't have permission to create a directory at the location where you are trying to save the data. You should either change the permissions of the location to get write access or comment out [this line](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh#L23) to avoid saving visualizations while evaluating.

**Comment by hlaahmed** [comment]
okay, i added sudo to the command, but now i have this error 
![image](https://user-images.githubusercontent.com/40806663/144460971-a0d99d89-249b-492f-9390-bd7665999dfe.png)

**Comment by hlaahmed** [comment]
The error was because I needed py-trees version less than 1.x
