### ISSUE TITLE
Hi, some questions about the model!

### ISSUE THREAD

**Issue by roger-cv** [autonomousvision/transfuser#35]
Hi, Thanks for this nice work. Recently, I am trying to modify this excellent model to make it suit for my work. As you see, why the "average" operation is required here, the shape of the tensor changes from 64*64 to 8*8 after the "average" operation.  However, the shape of the tensor should be the 64*64 just like the description" fusion at (B,64,64,64)".
![QQ截图20211202152824](https://user-images.githubusercontent.com/31872115/144378320-391663c2-edb6-4e68-84e9-7e86bcd281c3.jpg)

**Comment by ap229997** [comment]
The fusion can also be done at 64x64 resolution but that would be too computationally expensive since a transformer is used (quadratic complexity due to attention), so reduce the size to 8x8 at each resolution of the intermediate feature maps.

**Comment by roger-cv** [comment]
> 
Thanks for your quick reply. I guess that the input feature map of the transformer of each layer will be downsampled to 8*8 according to what you mean?

**Comment by ap229997** [comment]
that's correct, now there are several variants of transformer which address the quadratic complexity issue of the transformer (eg. [Linformer](https://arxiv.org/pdf/2006.04768.pdf)) so maybe it's possible to use the transformer without downsampling.

**Comment by roger-cv** [comment]
> that's correct, now there are several variants of transformer which address the quadratic complexity issue of the transformer (eg. [Linformer](https://arxiv.org/pdf/2006.04768.pdf)) so maybe it's possible to use the transformer without downsampling.

Ok, Another interesting question is that can this fusion fashion based on the transformer be replaced with other transformers, such as swim or PVT. Because I notice that this transformer is developed based on the GPT suited for the NLP area.

**Comment by ap229997** [comment]
I agree, architecture design can be improved quite a bit.

**Comment by roger-cv** [comment]
Ok, Nice work, Thanks for your reply.

**Comment by Kin-Zhang** [comment]
But it may require more resources to train...

> I agree, architecture design can be improved quite a bit.
