### ISSUE TITLE
Question about the version of the dataset provided for downloading.

### ISSUE THREAD

**Issue by GuillermoHan97** [autonomousvision/transfuser#46]
Thanks for the awesome work! 

I have a question regarding to the dataset. In Transfuser+ it proposed a new agent named 'SEED' and regenerated a training dataset using 'SEED'. So I'd like to know whether the dataset provided for downloading in this repo is the one generated by Transfuser+'s 'SEED', or it is the one generated by original Transfuser Agent?

Thanks in advance :).

**Comment by ap229997** [comment]
The provided dataset is generated by the autopilot agent from the original transfuser repo.

I did not understand what you mean by 'a new agent named SEED'. Can you clarify?

**Comment by GuillermoHan97** [comment]
Thanks for your quick reply! 

No warries, I misunderstood before. I assumed that the dataset was generated with the Transfuser+'s autopilot agent but this is actually not the case.
