### ISSUE TITLE
terminate called after throwing an instance of 'clmdep_msgpack::v1::type_error'   what():  std::bad_cast

### ISSUE THREAD

**Issue by raozhongyu** [autonomousvision/transfuser#5]
Hi, thanks for your great work. I meet this error when i collect the data, amd how much the data is enough

**Comment by ap229997** [comment]
Can you share a screenshot of the error? Does this error occur on the server side or the client side?

All of our models are trained on ~130k frames from 8 towns and 14 weather conditions.

**Comment by raozhongyu** [comment]
Thanks for your reply so fast,  this issue is probably related to this other one, which is a memory leak issue at the LB. [https://github.com/carla-simulator/leaderboard/issues/81](url)

**Comment by ap229997** [comment]
I remember seeing this error a few times on the CARLA server side but I haven't figured out the cause or a workaround. It's probably related to the GitHub issue you pointed out. At least in my case, this error was not too frequent, so I'd just restart the server and evaluation.

**Comment by raozhongyu** [comment]
Thanks for your reply, i will try it

**Comment by raozhongyu** [comment]
Hi, I'm sorry to ask you another question. I'd like to change the label and size of topdown, but I don't find where to change it in auto_pilot.py and map_agents, can you give me some suggestions. Thanks a lot.

**Comment by ap229997** [comment]
You can change different parameters of the topdown semantic map in [map_agent.py](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/team_code/map_agent.py#L14)

**Comment by raozhongyu** [comment]
I only find the traffic signs, how can i change the vehicle and buildings

**Comment by ap229997** [comment]
The vehicles and building classes are already present in the topdown semantic map that you get from CARLA. Traffic lights and stop signs need to be drawn separately because they are not visible in the topdown view.

**Comment by raozhongyu** [comment]
Thanks a lot. I get it.
