### ISSUE TITLE
How to realize the attention maps？

### ISSUE THREAD

**Issue by Watson52** [autonomousvision/transfuser#50]
Hi, thanks for your wonderful work especially the detailed code! But I am confused and have some questions about the attention maps. I only have a general understanding of the mechanism of Tranformer. I want to know how to understand the tokens mapping between images and lidar. Specifically, 
1. In the  supplementary, I think these are the same two scenarios, but the green areas appear in two different places when you query the traffic lights in the same location. How do you explain this phenomenon?
![1646912193(1)](https://user-images.githubusercontent.com/42103990/157656024-10927e3a-b67c-41e5-a7be-f17839f6fb99.jpg)

2. Also, in the circled scene above, does the green area in the lidar map change if the traffic light in the image is red? That is to say, does agent's focus change as the traffic lights change?
3. Finally, I just feel confused and can you explain why the lidar is mapped to this location in a situation like this?
![image](https://user-images.githubusercontent.com/42103990/157656146-b25038a4-9ff8-471f-8057-adb212e00e48.png)

Thank you in advance for your answer!

**Comment by Watson52** [comment]
Thank you for your quick response. But I still don't quite understand about the third point that sides of the intersection are mapped to each. Could you please give me some other examples about the visualizations?

**Comment by Watson52** [comment]
I see. I will try to run the code later and ask you when I meet a problem. Thank you! Btw, is there another way to download the dataset? I download it slowly on Amazon or sometimes I can't connect to it.

**Comment by ap229997** [comment]
Unfortunately, there is no other way to download the dataset.

**Comment by Watson52** [comment]
I see. Thank you :)
