### ISSUE TITLE
About the expert in the result

### ISSUE THREAD

**Issue by Watson52** [autonomousvision/transfuser#51]
Hi, I want to know that the expert with so high score in the result is because of its privileged information? I guess the expert is the agent from the first stage of the LBC.

**Comment by ap229997** [comment]
Yes, expert uses privileged information but it is different than the first stage (teacher model) of LBC. Expert uses A-star planner and collision avoidance heuristics to drive.

**Comment by Watson52** [comment]
I see. Well, what if the expert did not have privileged information? Or what do you think of the result with the A-star planner and collision avoidance heuristics?

**Comment by ap229997** [comment]
The current expert is still not perfect and suffers some infractions since there are certain loopholes in the heuristics.

**Comment by Watson52** [comment]
Thanks! I see.

**Comment by Watson52** [comment]
Hi again.
I try to realize the LBC but I didn't quite get it especially the 'topdown'. As you say that the dataset you provided could not train the LBC because of topdown. Could you please tell me what does it mean? Your repply with be appreciated.
