### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by hlaahmed** [autonomousvision/transfuser#52]
Hello
Which dataset did you use in training to get the weights in model-ckpt?
Is it 14-weathers-minimal-dataset ?

**Comment by ap229997** [comment]
The transfuser checkpoint is trained on a different dataset than the ones provided in this repository. We are currently unable to share the entire dataset.

**Comment by hlaahmed** [comment]
What about late fusion checkpoint?

**Comment by hlaahmed** [comment]
Thank you

**Comment by hlaahmed** [comment]
Hii
I downloaded clear weather dataset
But when I tried to train my model on it
I got this error
I am sure I replaced all paths with mine 
Is the data corrupted ? 
![EF08A9EE-0B32-4376-838D-1F5E3A68D7D0](https://user-images.githubusercontent.com/40806663/158909915-bf063082-f725-4f07-903a-b5002c75d66f.jpeg)

**Comment by ap229997** [comment]
You need to regenerate the preload file, just change the filename `rg_lidar_diag_pl_` to something else in `data.py` of the model directory that you are training
https://github.com/autonomousvision/transfuser/blob/720c9b566f8b6fdeec991881e291833b1566af9f/aim/data.py#L33

**Comment by hlaahmed** [comment]
Thank you
