### ISSUE TITLE
Question about training data generation

### ISSUE THREAD

**Issue by KleinYuan** [autonomousvision/transfuser#55]
I followed the guide to have setup Carla and run the [run_evaluation.sh](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh), meeting the same issue as described in https://github.com/autonomousvision/transfuser/issues/26.

However, how the problem has been resolved is not clear to me.

Your training [config.py](https://github.com/autonomousvision/transfuser/blob/main/transfuser/config.py#L9-L17) seems expecting a folder structure of : 

```
Town01_small
Town01_tinty
Town02_small
Town02_tinty
......
```

which doesn't seem matching what the [run_evaluation.sh](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh) is generating:

```
experts (or whatever you put at line 23 at run_evaluation.sh)
 - routes_town05_short_xxxxx
 - routes_town05_short_....
```

Are there any steps missing ? Do I expect to change the [line 23](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh#L23)/[line18](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh#L18) manually multiple times to have a datasets as you described in the paper? Then am I also expected to change the folder structure parsing in the [run_evaluation.sh](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/scripts/run_evaluation.sh) ?

**Comment by ap229997** [comment]
There are [several routes](https://github.com/autonomousvision/transfuser/tree/main/leaderboard/data/training_routes) for training corresponding to different towns and you need to manually run the generation script for each of them separately (also change L23 in `run_evaluation.sh`.
