### ISSUE TITLE
A question about the coordinate system of the camera and lidar

### ISSUE THREAD

**Issue by wcshen** [autonomousvision/transfuser#57]
Because the installation yaw of the lidar is -90°, i transform the lidar coordinate from "right-forward-top" to "forward-left-top" through:
`pcds = np.load(lidar_dir + lidar_files[frame]).reshape([-1, 4])
 temp = pcds[:, 0].copy()
 pcds[:, 0] = pcds[:, 1]
 pcds[:, 1] = -temp`
 and then visualize the lidar BEV and corresponding front camera images(the white dot is current target point): 
![flip](https://user-images.githubusercontent.com/38600406/159883973-b6722dee-dc0b-4b54-8257-63b964239850.png)
In the lidar BEV,the vehicle is turning left,but is turning right in the front camera? 
The data was generated through the script in this repo.

**Comment by ap229997** [comment]
Which version of CARLA are you using and why are you doing `pcds[:, 1] = -temp`?

**Comment by wcshen** [comment]
CARLA version:0.9.10
I want to transform the lidar coordinate from "right-forward-top" to "forward-left-top:
![image](https://user-images.githubusercontent.com/38600406/159938556-e17c61bc-f144-4c71-b973-f4d36fc56d84.png)

**Comment by ap229997** [comment]
Now, I get your point. I remember that the coordinate system in CARLA was a bit weird as some axes were inverted and we also faced issues when transforming coordinates. We just corrected for these inversions in our code (in data.py).
https://github.com/autonomousvision/transfuser/blob/720c9b566f8b6fdeec991881e291833b1566af9f/transfuser/data.py#L226-L243

I agree this is a bit confusing but you also need to correct for these inversions during visualizations.

**Comment by wcshen** [comment]
thanks！

**Comment by Kait0** [comment]
To add to this, the default coordinate system in CARLA is x front y right (z top) which is different from your drawing.
It's a bit hidden but you can check this in the official docs https://carla.readthedocs.io/en/0.9.10/python_api/#carlarotation
Like you said the LiDAR is rotated by 90°, so the initial point cloud you get from the sensor is in y front, x left, (z top).
(You then also have to be careful with the visualization software as they expect a specific coordinate system when visualizing usually)
