### ISSUE TITLE
Is this model supports windows 10 ?

### ISSUE THREAD

**Issue by Aditya183** [autonomousvision/transfuser#6]

**Comment by Aditya183** [comment]
> The entire framework including CARLA and our code is tested on ubuntu. If you want to run it on windows, then you need to check [windows build for CARLA](https://carla.readthedocs.io/en/latest/build_windows/).

Thank you so much

**Comment by Kin-Zhang** [comment]
I tried this one on windows with download the dataset from author's readme here: https://github.com/autonomousvision/transfuser/blob/main/README.md#dataset
And it's fine on training windows, but I don't think the evaluation can run at windows since it need change a lots command on script.

**Comment by ap229997** [comment]
You need to check the [windows build](https://carla.readthedocs.io/en/0.9.10/build_windows/#carla-build) of CARLA and set the environment variables accordingly to get CARLA to work.
