### ISSUE TITLE
ModuleNotFoundError: No module named 'carla'

### ISSUE THREAD

**Issue by aishgupta** [autonomousvision/transfuser#63]
Hi, 
I have downloaded and installed CARLA as mentioned in the readme file. However, while running the code `./leaderboard/scripts/run_evaluation.sh`, it throws an error:

**_ModuleNotFoundError: No module named 'carla'._** 

I have already tried adding the path to the egg file in the leaderboard_evaluator.py.  Can anyone please help me with this?

**Comment by ap229997** [comment]
Can you verify that `CARLA_ROOT` is set to the right path in `leaderboard/scripts/run_evaluation.sh`.
