### ISSUE TITLE
question about weight decay in the transfuser?

### ISSUE THREAD

**Issue by Zakiyi** [autonomousvision/transfuser#68]
Hi there,
 Thank you for sharing your code and it is really interesting work. I have one question about the weight decay in your model.
I find the configure_optimizers() in the transfuser with a comment of:
      # separate out all parameters to those that will and won't experience regularizing weight decay
but it seems you did not use this setting during training. So does weight decay matter for the final result?

Best,
zhen

**Comment by ap229997** [comment]
We didn't use it for training so our results are independent of it. I don't know if the model would perform better or worse if weight decay is used.
