### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by Watson52** [autonomousvision/transfuser#69]
Hi,
when I try to train the Transfuser, I got the same error in #26. I have change the path in  `config.py` file. But I really do not know how to change the modify the `data.py` file to get use of the whole dataset `14_weathers_minimal_data` for training.
Looking for your help.

**Comment by ap229997** [comment]
https://github.com/autonomousvision/transfuser/blob/720c9b566f8b6fdeec991881e291833b1566af9f/transfuser/data.py#L40
Replace `rg_lidar_diag_pl_` in the above path with anything else. Let me know if this doesn't work.
