### ISSUE TITLE
the inference speed

### ISSUE THREAD

**Issue by wangchangquan** [autonomousvision/transfuser#70]
I  test the running speed under dataset evaluate，no run carla. My GPU is nvidia M40.
The inference  speed is only 6-7fps / s.
so why the inference speed is so slowly?  and what your speed under dataset evaluate and  Evaluation use carla?

**Comment by ap229997** [comment]
Can you describe more about how you are evaluating without running Carla.

For evaluation using CARLA, it took 12-16 hours on `town05_long_routes` on a GTX 1080 Ti. The evaluation speed also depends on how many evaluations you are running per gpu.

**Comment by Watson52** [comment]
> Can you describe more about how you are evaluating without running Carla.
> 
> For evaluation using CARLA, it took 12-16 hours on `town05_long_routes` on a GTX 1080 Ti. The evaluation speed also depends on how many evaluations you are running per gpu.

Hi, @ap229997 
have you tried to split the evaluation routes and evaluate on different Carla severs at the same time? Cause I think the evaluation takes a long time.

**Comment by ap229997** [comment]
Yes, you could surely do that if you have access to resources.

**Comment by Watson52** [comment]
> Yes, you could surely do that if you have access to resources.

Thanks! Only need to pay attention to the sever PORT and TM_PORT.

**Comment by Kait0** [comment]
> > Can you describe more about how you are evaluating without running Carla.
> > For evaluation using CARLA, it took 12-16 hours on `town05_long_routes` on a GTX 1080 Ti. The evaluation speed also depends on how many evaluations you are running per gpu.
> 
> Hi, @ap229997 have you tried to split the evaluation routes and evaluate on different Carla severs at the same time? Cause I think the evaluation takes a long time.

This is how we evaluated the routes in the extended paper. CARLA evaluation scales almost linearly with GPU as you can run each route on it's own GPU.

**Comment by Watson52** [comment]
Hi, @Kait0 .Do you know to run CARLA sever on the specified GPU?

**Comment by Kait0** [comment]
We used:
SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE={gpu_number} path/to/CarlaUE4.sh --world-port={some instance specific port} -opengl 
(OpenGL needed if CARLA version is 0.9.10.)
Otherwise check the CARLA docs https://carla.readthedocs.io/en/latest/adv_rendering_options/#off-screen-mode

**Comment by Watson52** [comment]
> We used: SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE={gpu_number} path/to/CarlaUE4.sh --world-port={some instance specific port} -opengl (OpenGL needed if CARLA version is 0.9.10.) Otherwise check the CARLA docs https://carla.readthedocs.io/en/latest/adv_rendering_options/#off-screen-mode

Thanks! It works for me! btw, run on specified GPU only support offscreen?

**Comment by Kait0** [comment]
Don't really know why one would want to run CARLA on multiple GPUs without off screen. I guess you would have multiple spectator cameras, but at that point you probably rather record data on your hard drive. Note that CARLA still renders everything properly in off screen mode. You just don't see it on a monitor.
