### ISSUE TITLE
evaluation Town05 short

### ISSUE THREAD

**Issue by anslt** [autonomousvision/transfuser#71]
Hello,
I found that the only routes_town05_long.xml is in leaderboard/data/evaluation_routes and there is no short routes. And the short routes in leaderboard/data/validation_routes has 32 routes which does not match your setting (10 routes) in paper. I would like to ask for the  short routes in paper. This is helpful for us to compare our results with the paper ones.

**Comment by ap229997** [comment]
Unfortunately, I can't find the exact route file used for the Town05 short evaluation right now. Sorry about that. I'd expect the results to be similar to this 32 routes file since the town map and route lengths are similar, so you could still use this for comparison.

**Comment by anslt** [comment]
Thank you!
