### ISSUE TITLE
The readme link cannot find the page

### ISSUE THREAD

**Issue by Kin-Zhang** [autonomousvision/transfuser#75]
https://github.com/autonomousvision/transfuser/tree/2022/leaderboard#carla-leaderboard-09101

please check whether the link can be processed.

- https://github.com/avg-dev/transfuser/blob/c3899e6182896ec0fea9961f26f67974fba864b7/leaderboard/leaderboard/scenarios/route_scenario_local.py#L449
- https://github.com/avg-dev/transfuser/blob/c3899e6182896ec0fea9961f26f67974fba864b7/leaderboard/leaderboard/utils/statistics_manager_local.py#L26

**Comment by kashyap7x** [comment]
Here are the correct links:
https://github.com/autonomousvision/transfuser/blob/ff02e6fffa961e473a6a6486f387582349dc7f44/leaderboard/leaderboard/scenarios/route_scenario_local.py#L449
https://github.com/autonomousvision/transfuser/blob/ff02e6fffa961e473a6a6486f387582349dc7f44/leaderboard/leaderboard/utils/statistics_manager_local.py#L26

**Comment by Kin-Zhang** [comment]
Thanks!
