### ISSUE TITLE
About RoutePlanner gps normalization

### ISSUE THREAD

**Issue by ajdroid** [autonomousvision/transfuser#80]
Hi -- thanks for all your work in releasing this code and that for the baselines. I noticed that in the [RoutePlanner](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/team_code/planner.py) you have a mean and scale that is used to normalize the gps from the sensor. 

It seems to have 2 values for 2 versions of carla. Where did you get this normalization information from? I'm trying to use this with a different version of carla (9.13) so I'm trying to find the equivalent. 
```python
        # self.mean = np.array([49.0, 8.0]) # for carla 9.9
        # self.scale = np.array([111324.60662786, 73032.1570362]) # for carla 9.9
        self.mean = np.array([0.0, 0.0]) # for carla 9.10
        self.scale = np.array([111324.60662786, 111319.490945]) # for carla 9.10
```
Thanks!

**Comment by ap229997** [comment]
check https://github.com/autonomousvision/transfuser/issues/48#issuecomment-1054376659

**Comment by ajdroid** [comment]
Thanks!
