### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by jdmdj1999** [autonomousvision/transfuser#82]
Hi, the data format in 3d_bbs is (2, 3), I want to know the meaning of each data, thank you
`array({'traffic_lights': [array([[1.06119980e+02, 3.24080017e+02, 1.03242189e-01],
       [5.00000000e-01, 5.00000000e-01, 2.00000000e+00]]), array([[8.56299362e+01, 3.16350067e+02, 1.03261717e-01],
       [5.00000000e-01, 5.00000000e-01, 2.00000000e+00]]), array([[7.57100143e+01, 3.33339996e+02, 1.04206540e-01],
       [5.00000000e-01, 5.00000000e-01, 2.00000000e+00]])], 'stop_signs': [], 'vehicles': [array([[122.66907501, 326.57409668,   0.75363076],
       [ -2.45672918,  -1.055324  ,   0.74861716]]), array([[ 88.44949341, 292.56576538,   0.73687565],
       [  1.07081927,  -2.40077512,   0.74418798]]), array([[ 88.42881012, 279.55599976,   0.75995862],
       [  0.98650136,  -2.26420338,   0.76241399]]), array([[ 9.43607635e+01,  3.26568726e+02,  5.66630185e-01],
       [-9.16106747e-01, -1.61764037e-01,  5.66229532e-01]]), array([[ 88.40385437, 266.19451904,   0.81063163],
       [  1.01278689,  -2.42962736,   0.82387588]]), array([[ 88.39709473, 272.97341919,   0.69370979],
       [  0.99431107,  -2.68708813,   0.70534939]]), array([[ 88.45133972, 307.27682495,   0.76109296],
       [  1.0108214 ,  -2.25252841,   0.76513581]]), array([[ 63.04709244, 326.603302  ,   1.01708186],
       [ -2.24082488,  -1.03280694,   1.01943933]]), array([[116.24372864, 326.62203979,   0.64459324],
       [ -2.35581923,  -0.9547115 ,   0.6504657 ]]), array([[ 88.44115448, 285.90377808,   0.80321062],
       [  1.06737934,  -2.51920107,   0.81084795]]), array([[ 76.89850616, 326.73928833,   0.76173782],
       [ -1.72068262,  -1.09025338,   0.75210659]]), array([[ 87.90195465, 326.96627808,   0.73510283],
       [  0.87063314,   1.95763573,   0.73831866]]), array([[101.26699829, 326.63247681,   0.75230163],
       [ -2.45099899,  -1.06388041,   0.75525963]]), array([[ 88.42832947, 299.26382446,   0.83741564],
       [  1.13040282,  -2.30237509,   0.82938159]])], 'pedestrians': [array([[ 92.09710693, 284.42990112,   0.95150089],
       [ -0.33994821,  -0.34005179,   0.93000001]])]}, dtype=object)`

**Comment by ap229997** [comment]
The 3D bounding box is represented by 6 parameters - 3 for location and 3 for extent. You can read more about it in [carla docs](https://carla.readthedocs.io/en/0.9.10/python_api/#carla.BoundingBox).

It is implementation in our code as:
https://github.com/autonomousvision/transfuser/blob/9d5ebf01f7b5f6e5c02ebe0cba423119c465b388/leaderboard/team_code/base_agent.py#L514-L559

**Comment by jdmdj1999** [comment]
thanks a lot
