### ISSUE TITLE
Training Issue: No such file or directory

### ISSUE THREAD

**Issue by heming7** [autonomousvision/transfuser#83]
Hello transfuser team

First, thank you for the work! I am now facing a issue when try to train the model with the downloaded 2022 dataset. I set the root_dir parameter in train.py to `'/home/username/Work/transfuser/data/coke_dataset_23_11'` but when I ran the train.py, I got the error that says `No such file or directory: '/home/username/Work/transfuser/data/coke_dataset_23_11/Routes_Scenario3_Town07_curved_Seed1000/Scenario3_Town07_curved_route5_11_23_20_22_45/rgb/lidar'`. It seems like it was finding a lidar folder under rgb folder which should not be existed. Is this something wrong with the data.py?

**Comment by Kait0** [comment]
Hi,
I think based on the paths you wrote the root_dir should be set to '/home/username/Work/transfuser/data'
The coke_dataset_23_11 folder is just one part of the dataset containing one particular scenario.

**Comment by heming7** [comment]
> 

Thanks. It works.
