### ISSUE TITLE
About command input in CILRS

### ISSUE THREAD

**Issue by Watson52** [autonomousvision/transfuser#84]
hi,
In CILRS, I think the cmd input should be at the current moment. But I find the CILRS agent using the `next_command` that is a few meters away. Am I reading this correctly? 
https://github.com/autonomousvision/transfuser/blob/9d5ebf01f7b5f6e5c02ebe0cba423119c465b388/leaderboard/team_code/cilrs_agent.py#L143-L144
Looking forward to your reply.

**Comment by Watson52** [comment]
For instance, when I run the agent, there is still some distance to the intersection, but the `command` input into the network has been changed to target point's. (I think it should be `4: follow lane` instead of `2 :right` on this part of the road)
![1](https://user-images.githubusercontent.com/42103990/179920103-335c1fb5-5c0e-4e45-81b2-123d22039879.png)

**Comment by Kait0** [comment]
That is a good observation.
We are aware of this problem.
The dataset is collected the same way as during inference, which means the model can learn to adjust to the early command switches. It also means that it is hard to change as you need a new dataset.
I think we ran an experiment on this problem during some other project but fixing it didn't make much of a difference so we kept it.
In the new 2022 dataset we have adressed this issue by using a command buffer, see the [autopilot](https://github.com/autonomousvision/transfuser/blob/849bf6ca365811741548bb8526d2de26fc8c940c/team_code_autopilot/autopilot.py#L93).

Ultimately the point at which the command changes can not be set perfectly (like right at the start of the intersection) as it is calculated with the sparse waypoints in CARLA 0.9.10 and they in principle do not appear / change at fixed locations.
As far as I know CILRS was developed in CARLA 0.8.4 where you would still get a precise command at every time step.
