### ISSUE TITLE
Dear author，the problem about data

### ISSUE THREAD

**Issue by BeautyCJ** [autonomousvision/transfuser#99]
I download the dataset by https://github.com/autonomousvision/transfuser/blob/cvpr2021/download_data.sh
I can not find the folder named by hdmap, is it right？And how can I get hdmap data? Thanks~~

**Comment by Kait0** [comment]
The folder is called topdown.
The image contains more information than just the HD-Map.
We use some code to only extract the road and lane markings from it.
You can check the [dataloader](https://github.com/autonomousvision/transfuser/blob/b7102769ba9c9dcdff7e6c18ee9a096604040510/team_code_transfuser/data.py#L175) to get an example on how to load the HD-Map.

**Comment by raozhongyu** [comment]
I notice that the bev is set as bev_array[10:12], I'd like to konw what's that mean
